### ISSUE TITLE
Use Google Maps API in custom widget

### ISSUE THREAD

**Issue by Zahma** [microsoft/PowerBI-visuals-tools#108]
Hello,
Currently, I'm trying to develop a custom visual thats uses the google maps API in order to display a map.
theoretically its simple to do, but as we need to respect the architecture, and the modalities of import, and since the documentation is very rare I don't know how to approach this.
First I have installed the necessary typings for maps google So that the methods become known. and then I included the API script within the HTML page, using innerHTML.

So after doing everything, and suposing that everything will work, I get this error:_

`VM35042 js?key=XXX&callback=initMap:98 Uncaught 
mc {message: "initMap is not a function", name: "InvalidValueError", stack: "Error↵    at new mc (https://maps.googleapis.com/m…XXX&callback=initMap:137:68"}`

Is there any way to declare the API within the architecture, I dont know maybe through tsconfig. Or any way that can solve my issue.

Thank you for your help.

**Comment by AviSander** [comment]
Hi, I'm not too clear about the issue at hand. I think you are missing references in package.json\tsconfig.json\pbiviz.json. please see https://docs.npmjs.com/files/package.json , https://www.typescriptlang.org/docs/handbook/tsconfig-json.html etc.

**Comment by r-k-b** [comment]
Remove the `&callback=initMaps` parameter¹, and instead change your script loader to fire it's own callback after the script is loaded. [jQuery's `.getScript()` function][getscript] shows how that can be implemented, or just [import][import] jQuery and use `.getScript()` directly.

[getscript]: https://api.jquery.com/jquery.getscript/
[import]: https://github.com/Microsoft/PowerBI-visuals/blob/master/Tutorial/ExternalLibraries.md

---
¹ Power BI messes with the `window` object, preventing us from putting a function where that script can call it.

**Comment by AleksSavelev** [comment]
Closing due to age
