### ISSUE TITLE
Inconsistency between PBI Desktop and PBI Online

### ISSUE THREAD

**Issue by m-manino** [Microsoft/PowerBI-visuals-tools#109]
Currently I am developing a custom visual. 

I am trying to obtain a consistent and interactive drilldown behavior. A behavior like the "histogram" default component would be perfect (the user can select data, then if [s]he clicks on "drill mode" can drill down contextual data).

Trying out the sampleBarChart component from the Microsoft's tutorial, I get a strange behavior:

- In PowerBI Desktop everything works as expected.
- In PowerBI Online (IE11/FF/Chrome) it does nothing.

Strangely enough, if I manually force the refresh of the data (by for example resising the visual - edit mode only) I get the right data! For this reason I guess a possible workaround would be a simple refresh... But AFAIK it is not possible to trigger a refresh on a visual by code...

I am attaching a pbix with a dumb dataset to reproduce the issue. I had to enable drilldown on the sampleBarChart visual: I simply added

```
"drilldown": {
	"roles": ["category"]
},
```
in the capabilities and built it. 

I have attached a sample PBIX that shows this behavior.

Marco
[bah.zip](https://github.com/Microsoft/PowerBI-visuals-tools/files/1067821/bah.zip)

**Comment by vtkalek** [comment]
Hi Manino,

Unfortunately you are right, there is a bug with drill “Expand” and “interactive mode” functions.
This bug only happens in specific scenarios when the value of the category you want to “Drill” is a date.

Thanks for notifying us, we already have a fix for this issue it will take a couple of weeks till it gets to production.

Thanks and sorry for the inconvenience,

**Comment by AviSander** [comment]
the fix will hit production in two weeks. thx.
