### ISSUE TITLE
Add documentation for DataReduction strategies, pagination, and dataVolume

### ISSUE THREAD

**Issue by darthtrevino** [Microsoft/PowerBI-visuals-tools#111]
https://github.com/Microsoft/PowerBI-visuals-tools/blob/c00546cc71e01c025696baedb186b0a68723da69/templates/visuals/.api/v1.7.0/schema.capabilities.json#L263

I'm writing a custom viz that needs to pull in more data than the default, which seems to be around 1k data-points. My initial cut used a 'window' dataReduction strategy to optimize which dimension was returned in full, but there wasn't any documentation on how to iterate the window through the dataset to request more chunks of data.

My second cut, which is working for the level of data I have now simply bumps the dataVolume to 6, which is the maximum value. In the client API here, the schema simply validates that it is a number between 1 and 6, and the documentation indicates the same, but that doesn't give any useful semantic information to a client. From the PBIClients source code, I can see that the default is 3 and that "High Volume" is 6, but even then I'm not sure what limitations are imposed by those settings.

The dataVolume attribute should indicate what thresholds and limitations it applies to retrieving data, and there should be some documentation on how to use the dataReduction strategies to iterate through large datasets.

**Comment by AviSander** [comment]
Hello - 
   there's a bit of info in https://github.com/Microsoft/PowerBI-visuals-core/wiki/Capabilities#data-roles--dataview-mappings.
We'll work adding more adding documentation during the next two weeks.
thx!
