### ISSUE TITLE
Consider publishing API d.ts files as a separate package under @types/powerbi-visuals

### ISSUE THREAD

**Issue by darthtrevino** [microsoft/PowerBI-visuals-tools#112]
They API is useful in and of itself, but it probably makes sense to separate it from the tooling that bootstraps a visual. Since TS 2.0, the @types NS has been reserved for typings projects, and that would be an idiomatic way to propage types. Generated projects can then just reference the the API level by a package.json dependencies entry instead of having a separate `.api` folder.

**Comment by darthtrevino** [comment]
Since you have JSON-schema files as part of the API, maybe DefinitelyTyped isn't the right solution. I'm not sure if you can put anything other than d.ts file in their repo.

Another option may be to structure this as a monorepo using Lerna

```
packages/
    /pbiviz-cli <The PBIViz CLI tool>
    /powerbi-visuals-api <Typings and Schemas for the PowerBI API>
    /powerbi-visuals-utils-*
    /powerbi-visuals-docs <What's currently in Microsoft/PowerBI-visuals>
```

**Comment by MyNameReallySux** [comment]
Hopefully, someone responds soon. Would love to have more es2015 module support as well. This would be a small step towards that.

**Comment by AleksSavelev** [comment]
Closing due to age
