### ISSUE TITLE
Don't install a generic self-signed certificate on developer's computers

### ISSUE THREAD

**Issue by ckarras** [microsoft/PowerBI-visuals-tools#115]
The procedure documented here https://powerbi.microsoft.com/en-us/documentation/powerbi-custom-visuals-getting-started-with-developer-tools/ asks to install a self-signed certificate as a Trusted Root Certification Authority. I assumed this would generate a new certificate and install it, but it seems it's the same certificate for everyone, and that its private key is available in GitHub. 

This introduces a major security risk, anyone could create new certificates with this private key and have them automatically accepted on the computer of anyone who has ever developed PowerBI custom visuals (and didn't notice the security issue it causes)

Instead, the tool should generate a new certificate specific to the user's local computer, or allow using an existing certificate.

**Comment by zBritva** [comment]
Hello @ckarras `pbiviz --create-cert` option to tools was added to create the new certificate. Please update the tools to 1.11.0 or higher.
