### ISSUE TITLE
Capabilities.objects does not support "text" type

### ISSUE THREAD

**Issue by itslenny** [Microsoft/PowerBI-visuals-tools#12]
There is an error in the capabilities schema for API v1.0.0 and v1.1.1 that causes a validation error when trying to add a property with the text type.

**Comment by itslenny** [comment]
This issue is because it is not in the list of acceptable required options for the type property.

**Comment by itslenny** [comment]
This issue is resolved in tools v1.1.0

**Comment by spatney** [comment]
https://github.com/Microsoft/PowerBI-visuals-tools/commit/608991cb0fc1e7d416bb587bbd5c828eeb4354f6
