### ISSUE TITLE
'Show DataView' has everything, options.dataViews[0] is missing most stuff

### ISSUE THREAD

**Issue by markive** [Microsoft/PowerBI-visuals-tools#13]
When I use the 'Show DataView' preview. Everything in Categorical or Matrix is there (I've tried setting the DataViewMappings both ways many times).

This is what I can see in 'Show DataView':
![Image of DataView Preview](https://i.imgsafe.org/71c41b748c.jpg)

I can't see any of this in what is passed to the update function, everything I would want is hidden behind ' __ proto __ :
![Image of options.dataViews[0]](https://i.imgsafe.org/71c47b07e8.jpg)

Is this a bug or am I doing something fundamentally wrong? I feel like I've tried everything and been through all the existing visualisations to see the different options I can try.

Here are my DataViewMappings:
![DataViewMapping-Screenshot](https://i.imgsafe.org/71d9b728bb.jpg)

**Comment by spatney** [comment]
Correct. The reason for that is DataView employs [prototypical inheritance](http://javascript.info/tutorial/inheritance). The viewer in the 'developer visual' flattens this so you can easily view it. Even though the browser debugger 'hides' it behind '__ proto __', it shouldn't affect the way you access the properties, and should work as a regular object.

**Comment by markive** [comment]
Thanks for the quick reply! Having developed mobile apps in JS for the last few years and never used the Chrome Debugger I hadn't seen that before! It greys __proto__ it out so it looked private or not really there to my eyes.

Loving the new tool set btw!
