### ISSUE TITLE
pbiviz validate broken

### ISSUE THREAD

**Issue by whitneyland** [microsoft/PowerBI-visuals-tools#134]
I believe the default functionality for visual validation is not working.  Repro:

Try "pbiviz validate" with no path and the code is supposed to gather the proper .pbiviz file from the dist folder.  However, it fails because it adds an extra comment to the path.

//  Original code, not working:
//              let packageName = [visualPackage.config.visual.name, '.pbiviz'];
//              let packagePath = path.join(visualPackage.basePath, 'dist', packageName.join());

// One possible solution:
                let packageName = visualPackage.config.visual.name + '.pbiviz';
                let packagePath = path.join(visualPackage.basePath, 'dist', packageName);

**Comment by zBritva** [comment]
`pbiviz validate` is outdated
