### ISSUE TITLE
npm install fails due to sha checksum integrity

### ISSUE THREAD

**Issue by clouddie** [Microsoft/PowerBI-visuals-tools#135]
Hi, I can't install powerbi-visuals-tools versions 1.7.2 or 1.7.1, the installation fails due to checksum integrity, any ideas why ? Thanks,

`npm ERR! code EINTEGRITY
npm ERR! sha1-GLUpH3eluPi18O9gYoEpVWXYLYI= integrity checksum failed when using sha1: wanted sha1-GLUpH3eluPi18O9gYoEpVWXYLYI= but got sha1-ss+e15un1gVhLSSDNl4dLOFAdf8=. (48628 bytes)`

**Comment by ignatvilesov** [comment]
What version of npm do you use?

**Comment by clouddie** [comment]
Hi, sorry for the late reply, am using npm 5.3.0, I haven't retried to install since

**Comment by ignatvilesov** [comment]
Could you please try to install powerbi-visuals-tools?

**Comment by clouddie** [comment]
Hi, thanks it worked !! I managed to install the latest version of powerbi-visuals-tools (1.7.4) !!
