### ISSUE TITLE
Importing Interfaces or Functions from other typescript file prevents finding IVisual types

### ISSUE THREAD

**Issue by clouddie** [microsoft/PowerBI-visuals-tools#136]
Hi, I just created a new visual (with version 1.6.6) with `pbiviz new`. I want to use a lib I created with d3, in typescript, but just importing two interfaces causes typescript to lose track of all types IVisual, IVisualUpdateOptions, etc. What is wrong ?

![image](https://user-images.githubusercontent.com/20913430/29307515-82f7ac26-81a2-11e7-8c80-49fae9d1f1e4.png)

**Comment by ignatvilesov** [comment]
PBIVIZ tools don't support ES2015 modules unfortunately.
You should import an external module by using window["ExternalModuleName"].

**Comment by clouddie** [comment]
Hi, thanks a lot for your answer !
