### ISSUE TITLE
pbiviz start Constructor is called with empty options parameter

### ISSUE THREAD

**Issue by ernestochaves** [Microsoft/PowerBI-visuals-tools#139]
I followed the tutorials to setup the most basic example, even downloaded the bar chart samples, but there is always a JS error because the options parameter is undefined. How are this "options" created and why are mine undefined?

**Comment by uve** [comment]
Hello @ernestochaves, could you please send your source code to Power BI Custom Visuals Support <pbicvsupport@microsoft.com>, we'll help to investigate the reason.

**Comment by ernestochaves** [comment]
@uve Would gladly do so, but it happens with any fresh project I make with pbiviz. I even downloaded the source from the bar chart example. I think it might have to do with the tools I am running. What I really need to do is know where are this options in the constructor parameters coming from, mine are not being passed.

**Comment by uve** [comment]
@ernestochaves Have you tried to run **npm install** command?

**Comment by ernestochaves** [comment]
I did, I got this 3 warnings right now: 
npm WARN visual@ No description
npm WARN visual@ No repository field.
npm WARN visual@ No license field.

Not sure if that's significant.

**Comment by uve** [comment]
please zip your project folder and send it to pbicvsupport@microsoft.com

**Comment by ernestochaves** [comment]
Already did. Again, I have the issue with a fresh new project using pbiviz new, so not sure if the code has issues. 

Thanks.

**Comment by uve** [comment]
The problem was related to using localhost:8080 site to debug custom visual instead of app.powerbi.com.

**Comment by ernestochaves** [comment]
I was stupidly trying to view the report visual as a standalone from localhost. Nikita kindly explained to me why it doesnt work that way. Thanks a lot.
