### ISSUE TITLE
When getting R script contents, byte order mark should be stripped after reading source files

### ISSUE THREAD

**Issue by camilo-cr** [microsoft/PowerBI-visuals-tools#144]
Hi all,

I was writing a custom R-script visual in Visual Studio, and as part of the visual I wanted to add some source script files with helper functions, in my script.r file I added them as

source('./r_files/flatten_HTML.r')
source('./r_files/plotly_helper.r')

I packaged it and worked fine on power bi desktop, however when trying it in the portal dev visual I kept  getting errors when the r script was executed ... interesting. I tried again by removing the new source file and pasting all the contents of my second file in script.r ... works, pasting them in flatten_HTML.r also works, just adding an empty file it and include as source in script.r ... fails again.

It took me a while to understand what was going on; the files that are generated in VS come with a byte order mark at the beginning of the file and the script that is generated when replacing the contents of each source file includes the BOM for each source that was replaced. Creating the script file in notepad and the including it works fine.

Should the method _getRScriptsContents in VisualBuilder should strip the BOM from the temp content (if it has one) after reading the source file? 

Thanks,

Camilo

**Comment by AleksSavelev** [comment]
Closing due to age
