### ISSUE TITLE
Drillthrough

### ISSUE THREAD

**Issue by firstredpepper** [microsoft/PowerBI-visuals-tools#147]
When is the drillthrough feature going to be supported?

**Comment by uve** [comment]
Hello @firstredpepper,
 Do you mean drilldown feature?
https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/Drilldown.md

**Comment by firstredpepper** [comment]
Hi @uve no i mean drillthrough (new feature from a month or two ago). I posted the question on the Microsoft forum and just got a response recently - it seems like the feature is not supported through the API yet. 
https://community.powerbi.com/t5/Developer/Use-Drillthrough-in-Custom-Visual/m-p/268534

**Comment by Goofr** [comment]
Hi all,

I created a new idea on this topic:
[](https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/31998337-drill-through-on-custom-visuals)

Feel free to vote and comment on it.

Frank
