### ISSUE TITLE
`pbiviz` compilation does not work with `noImplicitAny: true`

### ISSUE THREAD

**Issue by Knagis** [Microsoft/PowerBI-visuals-tools#15]
The generated file `.tmp/precompile/visualPlugin.ts` includes a line:

        create: (options) => new powerbi.extensibility.visual.PBI_CV_33C9F325_D337_408C_98D4_E1D4E1EAD702.Visual(options),

which causes the error if `noImplicitAny` is enabled in `tsconfig.json`:

```
 info   Building visual...
 error  TYPESCRIPT  /visualPlugin.ts : (8,18) Parameter 'options' implicitly has an 'any' type.
```

**Comment by spatney** [comment]
commit ab4be92e6c1b8c4f27e3be52957aad46f6b5fc13
