### ISSUE TITLE
pbiviz start fails when starting watcher

### ISSUE THREAD

**Issue by szilardhuber** [microsoft/PowerBI-visuals-tools#157]
VisualBuilder.startWatcher method starts a watcher for all subfolders but it does not filter node_modules and it crashes with an unhandled error:

```
❯ pbiviz start
 info   Building visual...
 done   build complete
2018-01-11 13:11 node[89759] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2018-01-11 13:11 node[89759] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1018:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1420:11)
```

If I patch VisualBuilder.js on my machine to skip `node_modules` it works fine:

```
    startWatcher() {
        this.stopWatcher();
        return new Promise((resolve, reject) => {
            let basePath = this.visualPackage.basePath;
            let pathSlash = basePath.indexOf('/') !== -1 ? '/' : '\\';
            let basePathLength = basePath.length;
            //recursively add watchers (linux doesn't support recursive: true for a single watcher)
            fs.walk(basePath).on('data', item => {
                if (!item.stats.isDirectory()) return;
               
                //don't watch the node_modules folder as it can be huge
                if (item.path.indexOf(pathSlash + 'node_modules' + pathSlash, basePathLength) !== -1) return;
                
               //don't watch any hidden folders or their children
                if (item.path.indexOf(pathSlash + '.', basePathLength) !== -1) return;
                this.watchers.push(fs.watch(item.path, { recursive: false }, this._fileChangeHandler.bind(this)));
            }).on('end', () => {
                this.watcherInterval = setInterval(this._watchIntervalHandler.bind(this), 500);
                resolve();
            });
        });
    }
```

I will gladly create a PR for this if you confirm that watching node_modules is not something you would want here.

**Comment by uve** [comment]
@szilardhuber are you running pbiviz tool on MacOS machine?

**Comment by szilardhuber** [comment]
@uve Yes, that's correct. macOS 10.13.2 and pbiviz api version v1.10.0

**Comment by uve** [comment]
@szilardhuber it's [know issue](https://stackoverflow.com/questions/19981065/nodejs-error-emfile-too-many-open-files-on-mac-os) for MacOS

**Comment by szilardhuber** [comment]
@uve I have set up `ulimit -n 10240` which is the maximum I could get without changing kernel configuration which I'd rather not do. And it still crashes.

But on the other hand do you really think it is necessary to watch node_modules? As I understand there is a separate watcher generated for each and every folder even under node_modules. I personally don't expect the viz to be auto-rebuilt when the node_modules folder changes but maybe I'm alone with this.

**Comment by szilardhuber** [comment]
@uve couldn't it be a parameter to which folders to exclude from watching if you don't want to default on excluding node_modules? I think saying that "you should change your kernel config" is not so developer friendly and it is not just me but all the current and potential future developers of the plugin I'm working on.

**Comment by uve** [comment]
@szilardhuber, it's good idea to add an additional parameter to pbiviz tool. We'll consider it in the next versions of pbiviz tool.
Also there is another option, try to reduce amount of npm packages used in your project, it should help to run pbiviz tool on MacOS

**Comment by petispaespea** [comment]
I have encountered this issue as well. As `fs.watch` is implemented platform dependently I would suggest implementing startWatcher() in a platform dependent way too by utilizing the recursive capability of fs.watch.

**Comment by AleksSavelev** [comment]
Closing due to age
