### ISSUE TITLE
Exceptions from debug visual are silently caught and "eaten".

### ISSUE THREAD

**Issue by Knagis** [Microsoft/PowerBI-visuals-tools#16]
If the custom visual code throws an error, the powerbi host catches it and silently ignores (or I assume logs it somewhere). The result is that during development no errors are being shown in the browser console.

**Comment by spatney** [comment]
It does, you either put a try-catch around it, or a method decorator like this to make this easy to re-use. 

```
module powerbi.extensibility.visual {
    export function logExceptions() {
        return function (target: any, key: string, value: any) {
            return {
                value: function () {
                    let p = window.performance.now();
                    let result;
                    try {
                        result = value.value.apply(this, arguments);
                    } catch (e) {
                        console.error(e);
                        throw e;
                    }
                    return result;
                }
            }
        }
    }
}
```

and use it like this on the method you would like to log exceptions for.

```
@logExceptions()
public update(options: VisualUpdateOptions) {
```

We'll probably add a module for helpers like these soon enough.

**Comment by itslenny** [comment]
Thanks for pointing this out, @Knagis 

There are a few techniques you can use for debugging your visual. I've added a page to the docs to explain them all: [Debugging Guide](https://github.com/Microsoft/PowerBI-visuals-docs/blob/master/tools/debugging.md)

**Comment by Knagis** [comment]
This only handles the cases when the error is caused by code directly called from the visual. In this case the decorator approach would work. 

However, if I use a library that uses `setTimeout` or `requestAnimationFrame` and fails there, the error would still be lost. Perhaps there is a way to get all errors logged by the host to be shown in the console. Even if that shows way too much information it would allow to quickly check if there are any errors when something seems not to be working.
