### ISSUE TITLE
"pbiviz --install-cert" is broken on 1.11.0 in Windows 10

### ISSUE THREAD

**Issue by bitnovus** [Microsoft/PowerBI-visuals-tools#166]
Hello!

In Windows 10, it looks like **generateCert.ps1** in createCertFile (https://github.com/Microsoft/PowerBI-visuals-tools/blob/master/bin/pbiviz.js#L165) only generates a pfx file, but "--install-cert" is looking for a non-existent crt file.

I believe a potential fix is to change **certPath** to **pfxPath** https://github.com/Microsoft/PowerBI-visuals-tools/blob/master/bin/pbiviz.js#L208.

Error message:
```
PS C:\Users\ ... > pbiviz --install-cert
start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ start C:\Users\ ... \AppData\Roaming\npm\node_modules\powerbi-vi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

 info   Certificate path: C:\Users\ ... \AppData\Roaming\npm\node_modules\powerbi-visuals-tools\certs\PowerBICustom
VisualTest_public.crt
```

Downgrading to 1.10.1 is my current workaround.

Thanks!

**Comment by zBritva** [comment]
Hello @bitnovus 

Could you execute `pbiviz --create-cert` command? The command generates the new certificate.

**Comment by bitnovus** [comment]
Hi @zBritva 

Yes. Executing ```pbiviz --create-cert``` has no errors and successfully creates a **.pfx** file.

```
    Directory: C:\Users\ ... \AppData\Roaming\npm\node_modules\powerbi-visuals-tools\certs


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         3/4/2018   8:17 AM              0 blank
-a----        3/16/2018   5:13 AM           2622 PowerBICustomVisualTest_public.pfx
```

However, ```pbiviz --install-cert``` is looking for a **.crt** file:
https://github.com/Microsoft/PowerBI-visuals-tools/blob/master/bin/pbiviz.js#L199
https://github.com/Microsoft/PowerBI-visuals-tools/blob/master/config.json#L24

**Comment by zBritva** [comment]
@bitnovus it is enough. In windows env the tool uses PowerShell cmdlet. cmdlet creates the certificate in personal certificates directory. And --install-cert is not required. Try to launch dev server and debug the visual.

**Comment by jimsch71** [comment]
@bitnovus  I too am having this issue with a new install on Win10.  I was following a set of instructions here, 

https://docs.microsoft.com/en-us/power-bi/service-custom-visuals-getting-started-with-developer-tools

When you mention your workaround was 'Downgrade to 1.10.1, what are you exactly downgrading to? as the first steps in the instructions I'm following are to install Node.js with versions 8.10.0 and 9.8.0 are the only ones I see available.

**Comment by zBritva** [comment]
@bitnovus open the URL: https://localhost:8080/assets/status on the new tab and click to "Proceed to localhost".

Did you install tools locally or with `--global` flag?

**Comment by bitnovus** [comment]
@zBritva Thanks. That fixes the ```ERR_CERT_AUTHORITY_INVALID``` issue.

I installed the tools with the global flag.

**Comment by mattdot** [comment]
BTW, --install-cert generates the pfx with a random password (which we of course don't know) so we can't follow the old instructions of just installing the cert manually like we could when the crt and pvk were separate.

**Comment by zBritva** [comment]
@mattdot @bitnovus Fix is coming  https://github.com/Microsoft/PowerBI-visuals-tools/pull/167

**Comment by mattdot** [comment]
should also update these docs, because they're no longer accurate 
https://github.com/Microsoft/PowerBI-visuals/blob/master/tools/CertificateAddWindows.md

**Comment by zBritva** [comment]
@mattdot https://github.com/Microsoft/PowerBI-visuals/pull/307

**Comment by zBritva** [comment]
@jimsch71 did you execute `pbiviz --create-cert`? Did you try to launch dev server after that?

**Comment by greguz** [comment]
Same issue, downgraded to `powerbi-visuals-tools@^1.10` to fix the issue and install the certificate in Windows 10.

**Comment by zBritva** [comment]
@bitnovus @gregorybor @mattdot @jimsch71 
Hello, 

The fix was applied. 
The `--install-cert` command shows the message if cert file wasn't generated:
`info   Certificate not found. Call `pbiviz --create-cert` command to create the new certificate`
And the command tries to open cert or pfx file.

**Please update tools to 1.11.1 version**

Thanks!

**Comment by bitnovus** [comment]
Thanks @zBritva!

**Comment by a10k** [comment]
Windows 10 latest versions of all tools, still the same issue. just running pbiviz in powershell also shows the same error.

**Comment by srinivasbadepally** [comment]
C:\users\<userid>\AppData\Roaming\npm should in PATH variables otheriwse pbiviz is not recognized by the system as a command.... 

Use  below approach:
1. open command prompt: Start -> Run -> CMD
2. change directory to npm folder mentioned above
3. issue pbiviz --install-cert

you may chose to use Windows powershell, but I had hard time to take a note of the password generated for cert hence suggesting CMD prompt approach. 

Or, you can prefix pbiviz with full qualifier all the time and it should just work fine as long as this file is in the above mentioned directory

Hope this helps.
