### ISSUE TITLE
Clarify install steps

### ISSUE THREAD

**Issue by caaanerud** [Microsoft/PowerBI-visuals-tools#17]
The line: npm install -g powerbi-visuals-tools
Its not clear where the user is supposed to run this command line. What tool are they supposed to use. It assumes everyone knows where to run this command. Please clarify the tool being used. 

Thanks!

**Comment by spatney** [comment]
You can run it anywhere using any command-line tool (Terminal, Powershell, command prompt, etc). The only dependency you need is Node, which is already specified in the documentation. Something specific you'd like added/clarified?
