### ISSUE TITLE
table dataViewMapping does not respect the name attribute of dataRole

### ISSUE THREAD

**Issue by jo-tham** [Microsoft/PowerBI-visuals-tools#19]
Hi,

I have a dataViewMapping as below

```
{
    "dataRoles": [
        {
            "name": "category",
            "kind": 0,
            "displayName": "Style Field"
        },
        {
            "name": "latitude",
            "kind": 0,
            "displayName": "Latitude"
        },
        {
            "name": "longitude",
            "kind": 0,
            "displayName": "Longitude"
        }
    ],
    "dataViewMappings": [{
        "table": {
            "rows": {
                "select": [
                    {
                        "bind": {"to": "category"}
                    },
                    {
                        "bind": {"to": "latitude"}
                    },
                    {
                        "bind": {"to": "longitude"}
                    }
                ]
            }
        }
    }]
}
```

my understanding is that a `dataRole` `name` attribute is supposed to be bound to any field we assign to the data role.

so should be able to drag a field, say, `long` into `dataRole` with a `displayName` `Longitude`, which internally has `name` `longitude`

but, as shown in comparison of the 2 images below, my field has to have the name longitude in order for the dataview rows to be populated

here, where the field names do not match the dataRole names, the dataView rows is an empty array.

![screen shot 2016-08-09 at 4 06 28 pm](https://cloud.githubusercontent.com/assets/7353689/17536750/1532ecde-5e4c-11e6-9c29-5fd849bbd436.png)
 
here, the array is populated.

![screen shot 2016-08-09 at 4 07 01 pm](https://cloud.githubusercontent.com/assets/7353689/17536753/1b19f4da-5e4c-11e6-97a6-13d7a8dd4d02.png)

what do i need to do in order for the dataRole name to be respected in the select => bind => to: name definition in the capabilities above?

**Comment by jo-tham** [comment]
Hm, re-uploading the data resolved this issue... is it possible the data was deleted in powerbi?

**Comment by spatney** [comment]
maybe, though in general the 'name' property of datarole in the capabilities is only so you can refer to it in the mappings. It doesn't have the be the same as your column name.
