### ISSUE TITLE
Can't contact visual server.

### ISSUE THREAD

**Issue by ClarkDan** [Microsoft/PowerBI-visuals-tools#20]
When trying to set this up after dragging the test visual on a report I get this error:

Can't contact visual server

Dan

**Comment by spatney** [comment]
Make sure you have the [certs](https://github.com/Microsoft/PowerBI-visuals-docs/blob/master/tools/CertificateSetup.md) installed & have the [server running](https://github.com/Microsoft/PowerBI-visuals-docs/blob/master/tools/CertificateSetup.md)

**Comment by ClarkDan** [comment]
The certs installed correctly. This is what I get after pulling the test
visual in a report.
I followed these steps.

https://github.com/Microsoft/PowerBI-visuals-docs/blob/master/tools/DebugVisualSetup.md


[image: Inline image 1]

**Comment by spatney** [comment]
I can't see the image. Also, are there any errors in the console?

**Comment by ClarkDan** [comment]
Is the test image installed in a local directory?

**Comment by spatney** [comment]
test image?

**Comment by raananzvi** [comment]
Closing for now.

**Comment by mitagarg** [comment]
pbiviz start throwing error ......yu must be in the root folder of the server....
Certificate "localhost" is installed under "Trusted Root Certificate", have rebooted also....not sure what else to check. Aly help?

**Comment by oleg-vasilyev** [comment]
@spatney I had the same problem. All worked a couple of weeks ago, but now in all browsers except IE EDGE I have such a screen:
![image](https://cloud.githubusercontent.com/assets/24278912/26299849/f67dd180-3ee4-11e7-86b5-5ed025dad941.png)
Reinstalling the certificate does not help.

**Comment by Ozymandy** [comment]
@oleg-vasilyev I confirm. Have the same issue on my project right now

**Comment by ignatvilesov** [comment]
Please follow these steps to bypass the security issue:
- pbiviz start
- Open [https://localhost:8080/assets/status](https://localhost:8080/assets/status) in Google Chrome
- Open the Advanced
- Click the Proceed to localhost (unsafe)
- Back to the report with your debug visual
- Reload visual code

**Comment by oleg-vasilyev** [comment]
@ignatvilesov Worked, thank you very much!

**Comment by r-k-b** [comment]
[This info](https://stackoverflow.com/a/43665244/2014893) may be relevant: 

> To fix this, you need to supply an extra parameter to `openssl` when you're creating the cert, basically
> 
> `-sha256 -extfile v3.ext`
> 
> where `v3.ext` is a file like so, with `%%DOMAIN%%` replaced with the same name you use as your `Common Name`.  More info [here](https://textslashplain.com/2017/03/10/chrome-deprecates-subject-cn-matching/) and [over here](https://alexanderzeitler.com/articles/Fixing-Chrome-missing_subjectAltName-selfsigned-cert-openssl/)
> 
> 
> 
> ### v3.ext
>     authorityKeyIdentifier=keyid,issuer
>     basicConstraints=CA:FALSE
>     keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
>     subjectAltName = @alt_names
>      
>     [alt_names]
>     DNS.1 = %%DOMAIN%%
> 
> Note: Scripts that address this issue, and [create fully trusted ssl certs for use in Chrome, Safari and from Java clients can be found here](https://stackoverflow.com/a/43666288/26510)

**Comment by AviSander** [comment]
This has been fixed in the latest version of the toolset (1.7). We've updated the certificate. 
thx.

**Comment by ww2406** [comment]
I'm continuing to have this issue on OS X. It is not using the default localhost certificate and is instead generating a new certificate. The generated certificate does not include the Subject Alt Name field, making it invalid in Chrome and Firefox.

**Comment by zBritva** [comment]
@ww2406 as workaround try to use solution from thread: https://stackoverflow.com/questions/58802767/no-proceed-anyway-option-on-neterr-cert-invalid-in-chrome-on-macos/58957322#58957322

**Comment by debeaveruser** [comment]
> Please follow these steps to bypass the security issue:
> 
> * pbiviz start
> * Open https://localhost:8080/assets/status in Google Chrome
> * Open the Advanced
> * Click the Proceed to localhost (unsafe)
> * Back to the report with your debug visual
> * Reload visual code
> 
> Please let us know if it works for you well.

worked for me

**Comment by ChrisSCoding** [comment]
> Please follow these steps to bypass the security issue:
> 
> * pbiviz start
> * Open https://localhost:8080/assets/status in Google Chrome
> * Open the Advanced
> * Click the Proceed to localhost (unsafe)
> * Back to the report with your debug visual
> * Reload visual code
> 
> Please let us know if it works for you well.

Worked for me as well, i have tryed it with the Microsoft Edge browser and this browser is working fine,

Thanks a lot! I apreciate it
