### ISSUE TITLE
support traditional capabilities declaration

### ISSUE THREAD

**Issue by samississipi** [microsoft/PowerBI-visuals-tools#21]
with legendary [Developer Tools](https://powerbi.microsoft.com/en-us/documentation/powerbi-custom-visuals-getting-started-with-developer-tools/), we could declare the capabilities in one of the following two ways:
- declare capabilities as a static member of the visual:

``` typescript
export class MyVisual implements IVisual {
    public static capabilities: VisualCapabilities = { ... };
    ...
}
```
- explicitly declare the visual plugin along with the capabilities:

``` typescript
export class MyVisual implements IVisual { ... }
export let myPlugin: IVisualPlugin = {
        name: 'Visual Name',
        class: 'MyVisual',
        capabilities: { ... },
        create: () => new MyVisual(),
};
```

in both ways we could create the desired capabilities **at runtime** according to our business logic. for example, we could define our visual settings in a declarative way and then map them to powerbi dataview objects at runtime (**see my next post**).

however, with the new tool, we could no longer benefit from this but could only declare **static** capabilities in pbiviz.json. if we want the similar flexibility I mentioned above, we have to perform a complicated preprocessing to generate proper capabilities description in configuration before build, which is not desired.

**Comment by spatney** [comment]
capabilities were always meant to be static, and not instance specific (thus the reason for them being in a static variable). Changing them at run time can produce undesired behavior during dataview transform since the Power BI clients expect them to be static.

We do want to allow custom visuals in the future to customize their query (change dataview mappings & roles). Could you give me an example of when you want to dynamically change dataview objects?

**Comment by samississipi** [comment]
thanks for reply!

I didn't mean to **change** dataview objects dynamically but to **generate** object descriptors at runtime according to my setting option requirements or some other state to be persisted.

here's the example I mentioned in the last post:
```typescript
class SettingService {

    // register type of visual setting
    public register(settingType);

    // convert registered settings to pbi dataview object descriptors
    public getRequiredObjects(): { [objectName: string]: DataViewObjectDescriptor };

    // other possible functions
    public save(setting);
    public load(settingType);
    ...
}

// decorator defines how to map setting to dataview object
@mapToPbiObject({objectName: "layout"})
class LayoutSetting {

    // decorator defines how to map setting option to dataview object property
    @mapToPbiProperty({propertyName: "overflow",default: "scroll"})
    public overflow: string;

    @mapToPbiProperty({propertyName: "minWidth",default: 20})
    public minWidth: number;
}

var settingService: SettingService;
settingService.register(LayoutSetting);

export class MyVisual implements IVisual {

    public static capabilities: VisualCapabilities = {

        // define data roles, dataview mappings and etc.
        ...

        // define dataview objects
        // generate required dataview object descriptors according to registered settings.
        objects: settingService.getRequiredObjects();
    }
}
```

there's similar requirement for other (inner) fields of capabilities such as the `conditions` field of `DataViewMapping` (element type of `dataViewMappings`). 
I have a visual with multiple roles and I have to decide valid combinations of the count of fields assigned to each role, and then generate a set of conditions. the result condition set might change on each update of business login in the future.

although `capabilities` must be defined before the visual initializing and be immutable in the whole lifetime of the visual, that doesn't mean `capabilities` have to be absolutely **static**, it could be **generated** dynamically just before the visual initializing as the traditional approaches, and this could benefit us from extra flexibility.

**Comment by samississipi** [comment]
Thanks for reply!

I didn't mean to **change** dataview objects dynamically but to **generate** dataview object descriptors at runtime according to my settings or some other states to be persisted.

here's the example I mentioned in the last post:
``` typescript
class SettingService {

    // register type of visual setting
    public register(settingType);

    // convert registered settings to pbi dataview object descriptors
    public getRequiredObject(): { [objectName: string]: DataViewObjectDescriptor };

    // other possible functions
    public save(setting);
    public load(settingType);
    ...
}

// decorator defines how to map setting to dataview object
@mapToPbiObject({objectName: "layout"})
class LayoutSetting {

    // decorator defines how to map setting option to dataview object property
    @mapToPbiProperty({propertyName: "overflow",default: "scroll"})
    public overflow: string;

    @mapToPbiProperty({propertyName: "minWidth",default: 20})
    public minWidth: number;
}

var settingService: SettingService;
settingService.register(LayoutSetting);

export class MyVisual implements IVisual {

    public static capabilities: VisualCapabilities = {

        // define data roles, dataview mappings and etc.
        ...

        // define dataview objects
        // generate required dataview object descriptors according to registered settings.
        objects: settingService.getRequiredObject();
    }
}
```

there's similar requirement for other (inner) fields of `capabilities` such as `conditions` field of `DataViewMapping` (which is the element type of `dataViewMappings` field).
I currently work on a visual with multiple roles, for which I have to decide all valid combinations of the count of fields assigned to each role, and then **generate** a set of conditions at runtime.

## conclusion

although `capabilities` must be defined before visual initializing and be immutable in the whole lifetime of the visual, that doesn't mean `capabilities` must be designed as **static**. it could be **dynamically generated** before the visual initializing just as traditional (two) approaches do, and this could benefit us with extra flexibility.

**Comment by AleksSavelev** [comment]
Closing since the new version of [powerbi-visuals-api](https://github.com/microsoft/powerbi-visuals-api) allows you to implement settings dynamically
