### ISSUE TITLE
dataViewMappings instance.dataViewMappings[0] is not exactly one from [subschema 0],[subschema 1]

### ISSUE THREAD

**Issue by frljx** [microsoft/PowerBI-visuals-tools#224]
powerbi-visuals-tools version is 2.1.1

document:
![image](https://user-images.githubusercontent.com/10876080/46754592-6b0f0380-ccf5-11e8-9137-0b4434292811.png)

but:
![image](https://user-images.githubusercontent.com/10876080/46754693-a4e00a00-ccf5-11e8-913a-34c29622f984.png)

I don't know how to configure multiple rules at “dataViewMappings” of capabilities.json.

help me, please

**Comment by lrlucchini** [comment]
@frljx , Did you ever figure out this issue? I'm having the same problem right now. Thank you!

**Comment by zBritva** [comment]
@frljx Hello, Power BI Custom Visuals API doesn't support multiple rules at “dataViewMappings”.
Why do you need to use multiple mappings?

**Comment by lrlucchini** [comment]
In my case I am building a custom Sankey chart. One dataviewmapping would
be the table with origin, destination, and value, and color of the links
the second would be a table of node names and colors. Am I doing this
wrong? I'm using a plotly function in R to do this.

I'm very new to this so any guidance would be appreciated.

**Comment by zBritva** [comment]
@lrlucchini you can use several categories, for example Sankey from Microsoft already have additional filed for labels:

https://github.com/Microsoft/powerbi-visuals-sankey/blob/master/capabilities.json#L16

You can extend it by using additional fields for colors of nodes (get color name from data).
To provide custom colors for links from data, you can use additional grouping:
https://microsoft.github.io/PowerBI-visuals/docs/concepts/dataviewmappings/ look to Example2

or bind colors into datapoints as in Sankey by Microsoft.
