### ISSUE TITLE
Regenerate the guid value in pbiviz.json each time a package is built

### ISSUE THREAD

**Issue by adriennn** [microsoft/PowerBI-visuals-tools#231]
Hello, 

with regards to this [thread](https://community.powerbi.com/t5/Developer/Problem-with-updating-an-existing-visual/td-p/312701) and other similar issues raised in the forums:

**Current behavior**: the visual's guid is not updated when the visual package is built and this prevents powerbi from using the new code when importing the newly modified package
**Expected behavior**: the guid should be changed at each build time so that powerbi recognizes the new version as an updated visual and loads/uses the code accordingly

**Steps to reproduce the error:**
1. edit your custom visual ts code
2. build it
3. import into pbi
4. use the visual on the canvas to visualize something
5. update your custom visual ts code
6. build it
7. import into pbi
8. use the visual on the canvas to visualize something and see that your changes aren't taken into account

edit: tested on pbviz api version 1.11.0

**Comment by helen508light** [comment]
It works for latest PowerBI Desktop as u expected(new package with the same guid attaching).
For PowerBI service you can change guid in pbiviz by yourself and build new package.

**Comment by stefan-schweiger** [comment]
As far as I can tell this does not work in PowerBI Desktop. When I import a visual with the same GUID the program tells me that it's updating the visual, but none of my new functionality is there.
After I change the GUID and do the same thing it works like expected.

**Comment by zBritva** [comment]
@stefan-schweiger Power BI downloads the current version from CDN. Change the GUID to see changes

**Comment by stefan-schweiger** [comment]
@zBritva I figured as much after playing around with different version and GUID settings. Still doesn't seem straight forward for me. If I specifically import a file I want to use the file version and not the CDN version.

**Comment by zBritva** [comment]
No, when you import from the file you just update visual version in the report. But Power BI still uses version from CDN. Yes, it's not clear for users, but it's behaviour of Power BI.
