### ISSUE TITLE
Problem with creating selectionids for table view

### ISSUE THREAD

**Issue by tominurmiainen** [Microsoft/PowerBI-visuals-tools#234]
I have been trying to use the code @ignatvilesov has recommended to use as a workaround. But in my case createSelectionId will always create the same id. So when selecting something from the visual it will always select the same item.

Here is the code I'm using:
`private getSelectionIds(dataView: DataView, host: ISelectionIdBuilder): ISelectionId[] { 
    return dataView.table.identity.map((identity: DataViewScopeIdentity, index: number) => {

        let categoryColumn: DataViewCategoryColumn = {

            source: dataView.table.columns[0],

            values: null,

            identity: [identity]

        };

        return host.withCategory(categoryColumn, index).createSelectionId();

    });
}`
I have checked index and categoryColumn / identity will change inside the loop, but the createSelectionId will returns the same as the first item's selectionId.

Is there something I'm missing?

**Comment by ignatvilesov** [comment]
Do you call `host.createSelectionIdBuilder` for each row?

**Comment by tominurmiainen** [comment]
I call it only in the constructor:
this.selectionBuilder = options.host.createSelectionIdBuilder();

**Comment by ignatvilesov** [comment]
You should keep the host to use to create a SelectionIdBuilder

**Comment by tominurmiainen** [comment]
So I should change the code in constructor to this one:

**Comment by tominurmiainen** [comment]
Tried that one -> no change

**Comment by tominurmiainen** [comment]
I'm using api version 1.10 for now, if that matters...

**Comment by tominurmiainen** [comment]
@ignatvilesov I tried it with this way

**Comment by tominurmiainen** [comment]
I removed the index using from withCategory function call and it seems to be working now.
