### ISSUE TITLE
api-version not matching

### ISSUE THREAD

**Issue by lihp123** [Microsoft/PowerBI-visuals-tools#242]
Hello everyone,
I'm having some  trouble with pbiviz  and using d3v5 with powerbi-visuals-tools v3, maybe someone can help me out.
The error I am getting is based on this Repo: https://github.com/Microsoft/PowerBI-visuals-sampleBarChart/tree/dev/next ,I didn't change any code. 
When I first do npm install and then pbiviz start I am getting this error:
 `error  VALIDATION   Invalid API Version v1.13.0`
Then I enter pbiviz update so that the .api Folder is created and run pbiviz start again, getting this error:
 `error  VALIDATION   The PowerBI-visuals.d.ts in your tsconfig.json must match the api version in pbiviz.json (expected: .api/v1.13.0/PowerBI-visuals.d.ts) `

I know its still a beta, but maybe someone knows whats wrong? The migrating guide by microsoft is also not working for me. Other pbiviz programs are running without a problem.

THanks a lot in advance
Phil

**Comment by lihp123** [comment]
Clarification: 
- the file and path `.api/v1.13.0/PowerBI-visuals.d.ts` exists
- when i specify the api path in tsconfig.json under files like this:
`"files": [
    ".api/v2.1.0/PowerBI-visuals.d.ts",
    "./src/barChart.ts"
  ]`
I am getting non-stop typescript errors, see screenshot attached. And I don't think thats the solution, because its also not done this way in the git repo?!
![pbiviz_error_2](https://user-images.githubusercontent.com/23552188/49294135-61fb1100-f4b2-11e8-9fb4-2a859728d106.PNG)

**Comment by lihp123** [comment]
Alright, this error happens if the wrong pbiviz version is used. 
I installed the new version in the project folder but the `pbiviz start` command still used the old pbiviz version, resulting in the described errors.
My fix was to just install powerbi-visuals-tools@beta globally, but guess theres a better way to solve this.

**Comment by lihp123** [comment]
just enter
`npm install -g powerbi-visuals-tools@beta`
and if it is still not working try to delete the .api folder in your working directory, then enter
`pbiviz update`
followed by
`pbiviz start`

**Comment by VaibhavAsher** [comment]
Thanks! Seems to work :)
