### ISSUE TITLE
Please provide proper documentation on beta versions(for example, there is no --create-cert)

### ISSUE THREAD

**Issue by vkbamania** [microsoft/PowerBI-visuals-tools#256]
Please provide proper documentation on beta versions.

I have just started using powerbi-custom-tools. In version 2.3, there was --create-cert command which creates a self-signed certificate but in version 3 it is absent. Can anyone help me understand how can I use the beta version? 
![image](https://user-images.githubusercontent.com/12770033/56947860-052c8100-6b4c-11e9-92fd-3b15333b2199.png)

**Comment by bhavesh-jadav** [comment]
There is no `--create-cert` in beta version. Use `--install-cert` to create and install certificate instead.

**Comment by zBritva** [comment]
@bhavesh-jadav The new tools uses cert from global instance of powerbi-visuals-package or generates new one on executing `pbiviz start` command.
