### ISSUE TITLE
This new tools can't be used for gallery visuals

### ISSUE THREAD

**Issue by proll** [Microsoft/PowerBI-visuals-tools#26]
Can'find a way to add thumbnail and screenshot images to pbiviz using tools.
It made pbiviz not gallery ready

**Comment by itslenny** [comment]
I think the screenshot and thumbnail should be included in the submission separately. I don't think there is any reason for them to be inside of the pbiviz file.

In the current model they can just be included in the e-mail along with the pbiviz. In the future the developer portal should have a way for the developer to upload / change screenshots and thumbnails independently from the visual implementation (pbiviz).

**Comment by proll** [comment]
Makes sense. Thank you. I'll change gallery publisher then
