### ISSUE TITLE
create certificate return error

### ISSUE THREAD

**Issue by luojiandan** [microsoft/PowerBI-visuals-tools#265]
system info:windows10 64bit
install pbiviz package is ok:
[https://raw.githubusercontent.com/luojiandan/powerbi/master/Image/powerbi-visuals-tools.png](url)

create certificate return error:
[https://raw.githubusercontent.com/luojiandan/powerbi/master/Image/error%20unknown%20option%20'--create-cert'.png](url)

can you helps me,thanks:)

**Comment by zBritva** [comment]
https://github.com/microsoft/PowerBI-visuals/issues/550#issuecomment-496818020

**Comment by luojiandan** [comment]
> [microsoft/PowerBI-visuals#550 (comment)](https://github.com/microsoft/PowerBI-visuals/issues/550#issuecomment-496818020)

yes,It's ok!
