### ISSUE TITLE
[FEATURE REQUEST] Ability to have inter-page linking

### ISSUE THREAD

**Issue by ChildishForces** [microsoft/PowerBI-visuals-tools#270]
There is currently no ability to navigate to other pages of a report within a custom visual, which seems like a MAJOR missing feature. Why is there no ability to link to other elements of reports? Is it planned? If so when can we expect it?

**Comment by ChildishForces** [comment]
We could use basic Anchor tags if we had the ability to specify report page URLs.

**Comment by zBritva** [comment]
No, visuals executes inside iframe by security reasons

**Comment by ChildishForces** [comment]
You don’t want to allow inter-page intra-report linking for “security reasons”? Visuals execute inside iframes for security reasons, sure, so why do you allow cross highlighting? Can you tell me what security threat linking to other pages within a report poses over cross highlighting?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ChildishForces** [comment]
It's possible for custom visuals to communicate to each other through the APIs you provide. I am asking if you will include one that allows us to navigate a report properly.

**Comment by ChildishForces** [comment]
For instance maybe a reportNavigationUtils that allows us to use a method to navigate to a report page based on index.

**Comment by zBritva** [comment]
I mean, you can't manipulate with report elements from the visual, because visuals are inside iframe. 
For cross highlighting visuals communicate with Visual API.

If you want to create a button in report to switch the report page, you can use buttons:
![image](https://user-images.githubusercontent.com/10897951/59268247-f4941e00-8c54-11e9-865a-cb1712dad261.png)

I will forward you question to Power BI Visual API developers (give similar API for visuals)

Or you can consider some hack workaround: 
https://community.powerbi.com/t5/Desktop/How-to-Page-Navigation-in-Power-BI-Desktop/td-p/42737/page/2

**Comment by ChildishForces** [comment]
Okay, so you are saying the Visuals API is capable of helping the other visuals communicate with each other. I am asking why there cannot be something similar to control the state of the report. What is it that you fear could happen as a consequence of being able to change report page? Ideally we are looking for an actual feature, not a hacky workaround. We cannot be the only people with these issues.

You could have it as a custom data type, part of capabilities.json, that allows the user to configure a page as a capability, allowing the visual no further information than the reference provided by the user. What would be the issue with that?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zBritva** [comment]
Currently, API doesn't support the functionality. I will forward you question to Power BI Visual API developers. Thanks!

**Comment by ChildishForces** [comment]
Thank you very much. Have a great day!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
