### ISSUE TITLE
 cannot read property 'indexof' of undefined

### ISSUE THREAD

**Issue by SunnyXiao** [microsoft/PowerBI-visuals-tools#282]
When i run ‘pbiviz start' , it's show error:'  cannot read property 'indexof' of undefined',,  what`s happend?

**Comment by zBritva** [comment]
Hello, could you copy full output of error? And which version of tools and node js do you use?

**Comment by MaAngelica** [comment]
Hi, 
I get this error too. Im trying to install the pbiviz package to use the Custom Visual with R and Power BI.

The full output is:
warn Local certificate not found.
warn Checking global instance of pbiviz certificate
error Cannot read property 'index0f' of undefined
 
Node version: 10.16.03
Power BI version: 2.73.5586.1101
R version: 3.6.1
Windows 7 - 64 bit

**Comment by uve** [comment]
hello @MaAngelica, this bug will be fixed in upcoming version of powebi-visuals-tools@3.1.7 soon.
