### ISSUE TITLE
JS stack trace

### ISSUE THREAD

**Issue by SunnyXiao** [microsoft/PowerBI-visuals-tools#284]
Hello, I used react and jquery datagrid plugin named pgGrid with powerBI-visuals-tools,  when i run "npm run start",
**it show errors as  follows，  How can I solve this problem?**
[12700:00000000003873C0]   550300 ms: Mark-sweep 1344.1 (1443.7) -> 1340.9 (1450
.7) MB, 459.9 / 0.0 ms  (average mu = 0.148, current mu = 0.020) allocation fail
ure scavenge might not succeed
[12700:00000000003873C0]   550818 ms: Mark-sweep 1354.7 (1450.7) -> 1341.8 (1446
.2) MB, 417.5 / 0.0 ms  (average mu = 0.171, current mu = 0.194) allocation fail
ure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000002968905C5C1]
    1: StubFrame [pc: 00000296890112B4]
Security context: 0x031e94b9e6e9 <JSObject>
    2: skipWhitespace [00000393AB810549] [E:\InstallStation\nodejs\node_global\n
ode_modules\powerbi-visuals-tools\node_modules\less\lib\less\parser\parser-input
.js:~23] [pc=000002968E1EC7F6](this=0x035884f0d481 <JSGlobal Object>,length=1)
    3: /* anonymous */ [00000393AB810701] [E:\InstallStation\nodejs\node_global.
..

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaS
cript heap out of memory
 1: 000000013FE8C6AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 000000013FE67416 node::MakeCallback+4534
 3: 000000013FE67D90 node_module_register+2032
 4: 000000014018189E v8::internal::FatalProcessOutOfMemory+846
 5: 00000001401817CF v8::internal::FatalProcessOutOfMemory+639
 6: 0000000140367F94 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 000000014035EF76 v8::internal::ScavengeJob::operator=+24550
 8: 000000014035D5CC v8::internal::ScavengeJob::operator=+17980
 9: 0000000140366317 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 0000000140366396 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 0000000140490637 v8::internal::Factory::NewFillerObject+55
12: 000000014050D826 v8::internal::operator<<+73494
13: 000002968905C5C1
![power2](https://user-images.githubusercontent.com/18277688/64769552-149deb00-d57e-11e9-8ca4-24c13eacea70.png)

**Comment by zBritva** [comment]
@SunnyXiao hello, the preoblem is here:
The file 
`~pqgrid/pqgrid.min.css`
has 
```css
.pq-drop-hover{background-image:url(.)}
```

![image](https://user-images.githubusercontent.com/10897951/64861039-a158af80-d637-11e9-8fce-9fa980330a55.png)

The tools try to resolve the url and load the image from `url(.)`, but `.` means current file/dir. 
It seems tools try to recursively load same file and fails with out of memory error.

Comment this row to resolve. After that you should receive list of another errors in the project.

**Comment by SunnyXiao** [comment]
@zBritva Thank you very much, this problem has been bothering me for several days, and now I have finally solved it.

**Comment by SunnyXiao** [comment]
@zBritva why are there so many errors  when i used pqgrid with tools？  I  used pqgrid with create-react-app， No problem at all
![TIM图片20190916120240](https://user-images.githubusercontent.com/18277688/64933897-ec620500-d879-11e9-8ac8-24c295f67eb2.png)

**Comment by SunnyXiao** [comment]
is there way to solve this problem? @zBritva

**Comment by zBritva** [comment]
@SunnyXiao did you fix all TS compiter issues and upload the latest sources into repo?

**Comment by SunnyXiao** [comment]
@zBritva  yes, I do

**Comment by zBritva** [comment]
@SunnyXiao I don't see same issue. Could you explain steps to reproduce? I see only issues related to use localstorage and CORS requests. Basic visual renders correctly: 

![image](https://user-images.githubusercontent.com/10897951/64949613-3a7b0680-d882-11e9-8414-5fc6a762c297.png)

**Comment by SunnyXiao** [comment]
@zBritva thx, it works now
