### ISSUE TITLE
Matrix: Subtotal property is missing in dev mode from request

### ISSUE THREAD

**Issue by KoBe321** [microsoft/PowerBI-visuals-tools#288]
When I run my custom visual in development mode, it won't request for subtotal values, however when I package and import it, it will. I'm using 3 fields: customer group name, customer name (belongs to a customer group) and discount. The attached picture shows the request for the discount field, which should have a subtotal value for each customer group name.

`package.json`
![json](https://user-images.githubusercontent.com/8909363/67568264-f8b86800-f72b-11e9-9087-434af833adb5.PNG)
`pbiviz.json`
![pbiviz](https://user-images.githubusercontent.com/8909363/67568331-31584180-f72c-11e9-80ed-10ecec9da35f.PNG)
`capabilities.json`
![cap1](https://user-images.githubusercontent.com/8909363/67568633-03bfc800-f72d-11e9-8d28-bd89609accdd.PNG)
![cap2](https://user-images.githubusercontent.com/8909363/67568638-07ebe580-f72d-11e9-99bc-a7a86fbfe44b.PNG)
request in `dev mode`
![request2](https://user-images.githubusercontent.com/8909363/67568656-15a16b00-f72d-11e9-8a1b-c997e6ca479d.PNG)
request in `packaged mode`
![request](https://user-images.githubusercontent.com/8909363/67568677-218d2d00-f72d-11e9-84ab-084fda67d6c6.PNG)

At the moment I'm working on a different custom visual using `powerbi-visuals-tools@3.1.1` and the issue is the same.

This might be the same issue:
https://github.com/microsoft/Powerbi-Visuals-SampleMatrix/issues/1

EDIT: Adding the difference of the request.
![diff2](https://user-images.githubusercontent.com/8909363/67748707-d4120800-fa2b-11e9-867a-944abced4ae4.PNG)

**Comment by KoBe321** [comment]
Hi @helen508light 
Thanks for the tip, but after modifying my `capabilities.json` to the following, it still doesn't work. _Subtotal_ is not requested nor received from the backend. 
![err1](https://user-images.githubusercontent.com/8909363/67878039-f8103f00-fb3a-11e9-966b-47b0c9fac898.PNG)
![err](https://user-images.githubusercontent.com/8909363/67878082-0a8a7880-fb3b-11e9-807e-c722f72ed5f7.PNG)

**Comment by AviSander** [comment]
hello  -the fix should be deployed by the end of this week.

**Comment by arunbera** [comment]
Hi- The issue still in latest API. Could anyone please update the status.

**Comment by zubairmvp** [comment]
Was the fix deployed? I am still not able to get subtotals work.
Also the sample Matrix Custom Visual doesn't work
https://github.com/microsoft/Powerbi-Visuals-SampleMatrix
