### ISSUE TITLE
Hide the [Confirm Navigation] dialog with custom visuals

### ISSUE THREAD

**Issue by hjfrun** [microsoft/PowerBI-visuals-tools#289]
![image](https://user-images.githubusercontent.com/4508489/67916284-27bd5680-fbd0-11e9-8338-eab46640fdaa.png)

Hi team,

I wrote a custom visual with a button inside, when the user click the button, it will navigate to another webside.

Is there a way to disable the prompt/confirmation? I don't want the user to see the link.

Thank you!

**Comment by helen508light** [comment]
@hjfrun 
it is not possible now

**Comment by hjfrun** [comment]
@helen508light Thanks, got it.
