### ISSUE TITLE
drill down in custom table visual

### ISSUE THREAD

**Issue by rajkumarui** [Microsoft/PowerBI-visuals-tools#29]
Please provide documentation for drill down implementation in a custom visual.

**Comment by soodik323** [comment]
Same question, is it possible to use drilldown atm ? with api version 1.1.0 ?

**Comment by tosta1989** [comment]
Hi Guys, 

Drill Down is now available in custom visuals. 
Here is the documentation on how to implement this ability:
https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/Drilldown.md
