### ISSUE TITLE
"fetch more" returns row cells in wrong order

### ISSUE THREAD

**Issue by KoBe321** [microsoft/PowerBI-visuals-tools#290]
Given these columns in the following order:
![cols good](https://user-images.githubusercontent.com/8909363/68400347-2cf24680-0178-11ea-899e-602c4753d4f4.PNG)

The first 1000 rows are returned correctly:
![rows good](https://user-images.githubusercontent.com/8909363/68400401-44c9ca80-0178-11ea-802f-176f2ae17cdc.PNG)

But after using the "fetch more" functionality, the next 1000 rows have their cells in the wrong order (the columns are still the same):
![bad res](https://user-images.githubusercontent.com/8909363/68400520-7a6eb380-0178-11ea-9743-6302bbdf8562.PNG)

EDIT:
There's a difference between the order of the columns in `metadata` and `table.columns`.
![col diff](https://user-images.githubusercontent.com/8909363/68467198-113d7d80-0216-11ea-8ebc-4175a3219aef.PNG)
The correct is `table.columns` where e.g. *Quantity* is the last. This is the same order as what we have in the fields.
![fields](https://user-images.githubusercontent.com/8909363/68467366-56fa4600-0216-11ea-9966-e7d812f07175.PNG)
This should be the order how the data is queried and received, but the API is using the `metadata`.
![req](https://user-images.githubusercontent.com/8909363/68467522-a2145900-0216-11ea-83fa-586901f5840e.PNG)
That's why the order of the rows is wrong when using `fetch`: It'll use the column order of the `metadata` instead of the `table.columns` (or the `metadata` is not updated).

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com) with questions related to development of custom visuals
