### ISSUE TITLE
Wrong VisualUpdateType returned

### ISSUE THREAD

**Issue by KoBe321** [microsoft/PowerBI-visuals-tools#291]
1. open your report
2. refresh the page
3. quickly navigate to a different tab
4. wait for your report to load (e.g. a console.log() has run in your update())
5. a VisualUpdateType of 62, 36 and 2 should have been seen if logged in update()
6. go to your report
7. trigger the fetchMore API
8. a VisualUpdateType of 36 will be returned for every fetchMore from now instead of 2

The bug occurs only if the page is loaded while you are navigated to a different tab, otherwise it's ok.

**Comment by helen508light** [comment]
@KoBe321 
Thank you for feedback
We had added this bug to our backlog and will consider your suggestions in the next versions of the visual
