### ISSUE TITLE
DataEntrySlicers is missing in Edge, IE

### ISSUE THREAD

**Issue by KoBe321** [microsoft/PowerBI-visuals-tools#292]
The property `DataEntrySlicers` is missing from `window.powerbi.visuals` in IE and Edge.

**Comment by helen508light** [comment]
powerBI API does not include such a property

**Comment by helen508light** [comment]
Could you please describe your problem in details? It doed not seems to be related to powerbi-visuals-tools directly

**Comment by KoBe321** [comment]
I'm sorry, you are right. That property is part of a different library.
I'll close the issue. :)
