### ISSUE TITLE
Installing resolves a Core-JS@2.3.0 is now deprecated

### ISSUE THREAD

**Issue by MikeCarlo** [microsoft/PowerBI-visuals-tools#298]
When running the install (npm install -g powerbi-visuals-tools) npm produces a warning that core-js@2.3.0 is no longer maintained.

Can an update to a newer version of Core-JS be used?

![1](https://user-images.githubusercontent.com/25160592/72810123-8e2ba100-3c22-11ea-8f29-e29cb8d0fa16.png)

**Comment by zBritva** [comment]
@MikeCarlo it's related to https://github.com/microsoft/powerbi-visuals-webpack-plugin package. 
and core-js used by old version jszip library.

Tool use core-js v3 when builds the visual:
https://github.com/microsoft/PowerBI-visuals-tools/blob/master/lib/WebPackWrap.js#L196

**Comment by MikeCarlo** [comment]
thanks so this is not an issue, and I should ignore the Warning?

**Comment by zBritva** [comment]
It doesn’t block you to develop visuals
