### ISSUE TITLE
Error while trying to install - Unexpected end of JSON input while parsing near '...s":"^1.0.2","semver"

### ISSUE THREAD

**Issue by vjcrypto** [microsoft/PowerBI-visuals-tools#301]
I had node version 12 installed originally and then tried to install powerbi-visuals-tools. Installation failed with an error that it wanted node version 10.0.0 and current was v12. So, I downgraded to see if that would work. It still fails but now with a different error.

![image](https://user-images.githubusercontent.com/11582603/75593960-b2ae4080-5a4c-11ea-99cf-a3f92700b742.png)

**Comment by helen508light** [comment]
is this issue still reproducible for you? Have tried for both 12.0.0 and 10.0.0 versions and it works as expected for me

**Comment by uve** [comment]
please install powerbi-visuals-tools@3.1.12
