### ISSUE TITLE
Support specifying a custom webpack.config.js

### ISSUE THREAD

**Issue by LinqLover** [microsoft/PowerBI-visuals-tools#303]
For certain scenarios, I would consider it helpful if you could specify your owner webpack configuration when developing a custom Power BI visual. For example, this would be helpful to import files via `require()` using customer loaders.

The only way at the moment to do this appears to be [setting up webpack completely manually](https://github.com/Microsoft/powerbi-visuals-webpack-plugin#powerbi-visuals-webpack-plugin) and leaving the comfort of pbiviz behind yourself (I did not yet try this out). It would be great if there was native support for extending the webpack configuration of your pbiviz server.

Possible related: microsoft/PowerBI-visuals#549

**Comment by zBritva** [comment]
Hello, 

You [can use](https://webpack.js.org/loaders/) the format:

`var moduleWithOneLoader = require("my-loader!./my-awesome-module");`

you have to install `my-loader!` package to your visual project.

If you want to use the lazy-loading or split code to chunks and load from CDN, it doesn't work due to limitation of Power BI side.  

You can [configure webpack ](https://webpack.js.org/configuration/output/#outputpublicpath) to load chunks from CDN, but it will not work in the visual. Webpack can't init loaded chunk properly.

Power BI team knows it, I think they will fix it in future.

**Comment by LinqLover** [comment]
Hi, thanks for the hint to the `!` syntax! Unfortunately, I cannot get it to work:

```ts
require('csv-loader!../static/myfile.csv');
```
Fails at compile time:
```
ERROR in ./static/myfile.csv (./node_modules/csv-loader!./static/myfile.csv)
Module build failed (from ./node_modules/csv-loader/index.js):
Error: Cannot find module 'papaparse'
Require stack:
- .\node_modules\csv-loader\index.js
- %APPDATA%\npm\node_modules\powerbi-visuals-tools\node_modules\loader-runner\lib\loadLoader.js
- %APPDATA%\npm\node_modules\powerbi-visuals-tools\node_modules\loader-runner\lib\LoaderRunner.js
- ...
```
Let me note that the following, however, compiles and runs without problems:
```ts
console.log(require('papaparse')); // works
console.log(require('csv-loader')); // works
console.log(require('file-loader!../static/myfile.csv')); // works
```
Also, all necessary dependencies should be installed:
```
npm list | wsl grep -E "'loader|papaparse'"
+-- @types/papaparse@5.0.3
+-- csv-loader@3.0.2
| `-- loader-utils@1.4.0
+-- file-loader@6.0.0
| +-- loader-utils@2.0.0
+-- papaparse@4.6.3
+-- ts-loader@6.1.0
| +-- loader-utils@1.4.0 deduped
  +-- loader-runner@2.4.0
  +-- loader-utils@1.4.0 deduped
```

Do you have any tips for me? :-)

---

Apart from that, I would keep this issue open until it has been implemented. Or is this a duplicate?

**Comment by zBritva** [comment]
@LinqLover I got the same issue. But it was resolved after installation papaparse too (call `npm install papaparse --save-dev`):

Uploaded the sample here:
https://github.com/zBritva/powerbi-visuals-webpack-loader-test/blob/master/package.json#L21

**Comment by LinqLover** [comment]
Ah, thank you, I missed the `--save-dev`! However, why shouldn't you use `--save` here instead? Won't this dependency be also required when the `.pbiviz` file will be used in production?

**Comment by zBritva** [comment]
No, for production or consuming in the dev visual, your csv file should be inside JS/JSON package. Loaders are responsible for that on compile/build time. In case of runtime loading - yes, you are right. But I don't know it is working for Power BI visual or not.

**Comment by LinqLover** [comment]
Alright, I was not talking about runtime loading. Thank you :)

**Comment by zBritva** [comment]
@uve I think you can consider to mention it in developers documentation. Thanks!

**Comment by danmarshall** [comment]
+1 on having ability to specify custom webpack.config.js. My scenario is that I have React as a peerDependency several components deep, and need to resolve React like this:
```
  alias: {
    react: path.resolve('./node_modules/react'),
    'react-dom': path.resolve('./node_modules/react-dom')
  }
```

**Comment by sgratzl** [comment]
my use case is to add https://webpack.js.org/plugins/define-plugin/ such that I can define some constants based on environment variables during build type. Any Ideas how to achieve that?

**Comment by smashmirrorcardboardface** [comment]
I'd like this also - old request i know.  but it would be good to be able to tell webpack not to minimise the scripts for debugging purposes.

**Comment by LasanthaKathriarachchi** [comment]
Hi Guys..

I wanted to embed/render a Vue template inside a power bi custom visual.
I could prepare the "webpack.config.js" with loaders like "vue-loader", "ts-loader" and other relevant loaders.
Also used the below code lines inside the constructor of power bi custom visual.

const vueApp = createApp(VueApp);
vueApp.config.compilerOptions.isCustomElement = (tag: string) => tag === 'helloworld';         
vueApp.mount(this.divMap);

No any error or warning displaying in debug console of browser.
But it doesn't render the content of my vue template "VueApp", into the custom visual. 
Only message I see in the browser console is below.

------
[webpack-dev-server] Server started: Hot Module Replacement disabled, Live Reloading enabled, Progress disabled, Overlay enabled.
------

Can any one advise on how to make it rendering.

Thanks..

**Comment by zBritva** [comment]
@LasanthaKathriarachchi you can create webpack project for the visual from scratch: 
See docs here:
https://github.com/microsoft/powerbi-visuals-webpack-plugin

**Comment by LasanthaKathriarachchi** [comment]
Hi zBritva,

I could already create the webpack and solved all the errors and warnings came before.

Now the problem is, content of the Vue template is not visible/render into the visual.
What could be the reason?

**Comment by LasanthaKathriarachchi** [comment]
These are the errors and warnings came before.

1) __VUE_OPTIONS_API__ , __VUE_PROD_DEVTOOLS__ are not explicitly defined.
2) Component is missing template or render function.

Now its not raising any error or warning when I checked with console.
But template content is not rendered.

Please let me know if any version issue or existing issue of vue/powerbi or any wrong thing in my side?

Thanks in advance..

**Comment by zBritva** [comment]
@LasanthaKathriarachchi  try to use my template: https://github.com/zBritva/powerbi-visuals-vue-template

**Comment by LasanthaKathriarachchi** [comment]
Hi zBritva..

Thank you for the response.
I used the same way as your vue template and visual.ts.
Then it raise this warning..

"[Vue warn]: Component is missing template or render function. 
  at <HelloWorld>"

It asking for a tag with the name of vue template "HelloWorld".

**Comment by zBritva** [comment]
I am not an expert in Vue,
According to the description 

![image](https://user-images.githubusercontent.com/10897951/198272974-3c7423a0-6f4b-4852-9129-f8e289c84ef9.png)

the `vueApp.config.compilerOptions` is parameters for `@vue/compiler-dom`

**Comment by LasanthaKathriarachchi** [comment]
Ok zBritva..

I'm going to build and run your source, in my power bi environment.
If it works, then I'll check what is the fault in my solution.

I'll let you know.
Thank you for your great support..

**Comment by LasanthaKathriarachchi** [comment]
Hi zBritva..

I tried your way as lang="js" instead of lang="ts".
Then it renders the template witch has only simple html tags and data binding within the template.

But my solution need it to be as lang="ts".
Because it has inner level Vue modules imported into entry level Vue module/template.

Then it doesn't render any thing.
I tried even applying  both "vue-loader" and "ts-loader" under the use section of  "test: /\.vue$/,"
It compiled but just render nothing in the visual.

Any additional configuration to use lang="ts" and to import and use inner level Vue modules/templates into entry level module.

Please let me know. Thanks..

**Comment by zBritva** [comment]
Got you. It needs additional configuration for typesctipt + vue  combination. I will try to modify my template for that.

**Comment by LasanthaKathriarachchi** [comment]
Ok zBritva.. 

Please let me know, what are the additional configuration, when it worked for you.
I tried this way too. But didn't work.

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent ({
  data () {
    return {
      msg: 'Hello Power BI!'
    }
  }
});
</script>

Thanks in advance.

**Comment by zBritva** [comment]
@LasanthaKathriarachchi 
I just added this 
https://github.com/zBritva/powerbi-visuals-vue-template/commit/0aac683eb56766a80a4ca2f1b78758422975cf83

And it works in my tempalte.

**Comment by LasanthaKathriarachchi** [comment]
Cool...
Now it works as lang="ts".
Setting   appendTsSuffixTo: [/\.vue$/]     was the secret.

Thank you very much, zBritva, for the great support.

**Comment by LasanthaKathriarachchi** [comment]
Hi zBritva..

I came-across another different issue now.
I tried cross-filte by cross-select as below.
--------------------------
let rowSelection: ISelectionId = this.visualHost.createSelectionIdBuilder()
                .withTable(this.dataView.table, rowIndex)
                .createSelectionId(); 
await this.selectionManager.select(rowSelection, true).then(result => {
            console.log(result);
        });
-------------------------------
 
result of then() is just like below
-------------------------

    [t]
        0: t
            dataMap:
                {"identityIndex":0}: [{…}]
                [[Prototype]]: Object
            deepestNodeLevelInPath: -1
            key: "{\"{\\\"identityIndex\\\":0}\":[{\"identityIndex\":0}]}[]"
            measures: []
            nodeIsCollapsed: null
            [[Prototype]]: Object
        length: 1
        [[Prototype]]: Array(0)--------------------------------

But this didn't cross-select the passed selectionID row in other visuals of the page.
What could be the reason. Any specific config setting in tsconfig, capabilities.json or webpack.config
Please advise.
 
Thanks in advance,
Lasantha

**Comment by zBritva** [comment]
@LasanthaKathriarachchi did you enabled filter API? 
https://learn.microsoft.com/en-us/power-bi/developer/visuals/filter-api

**Comment by LasanthaKathriarachchi** [comment]
Hi zBritva..

Thank you for response..
I installed this package too
npm install powerbi-models --save

Also applied the settings in capabilities.json as below.
"general": {
            "displayName": "General",
            "properties": {
                "selection": {
                    "displayName": "Selection",
                    "type": {
                        "text": true
                    }
                },
                "filter": {
                    "type": {
                        "filter": true
                    }
                },
                "selfFilter": {
                    "type": {
                        "filter": {
                            "selfFilter": true
                        }
                    }
                }
            }
        }

But didn't apply any settings in "pbiviz.json:" and "tsconfig.json:" as you mentioned in the link.
https://github.com/Microsoft/powerbi-visuals-sampleslicer/blob/master/doc/AddingAdvancedFilterAPI.md

Is that the reason?
I'll apply the changes in "pbiviz.json:" and "tsconfig.json:", check again.

I'll let you know..
Thanks.

**Comment by zBritva** [comment]
@LasanthaKathriarachchi 

Again.  **The selection API doesn't work with filter API**. 

You have to decide to build Filter visual or Typical visual. You can't build universal visual.

**Comment by LasanthaKathriarachchi** [comment]
Oh ok zBritva..

So do you mean to uninstall the below?
npm uninstall powerbi-models --save

Actually, before I install it, I tested only  with these coding. But it didn't work.

let rowSelection: ISelectionId = this.visualHost.createSelectionIdBuilder()
.withTable(this.dataView.table, rowIndex)
.createSelectionId(); 
await this.selectionManager.select(rowSelection, true).then(result => {
console.log(result);
});

Can you explain did this way work for cross-filter by cross-selection. That's how I want?
Please advise..

**Comment by zBritva** [comment]
@LasanthaKathriarachchi 

You need to remove

```JSON
filter": {
"type": {
"filter": true
}
},
"selfFilter": {
"type": {
"filter": {
"selfFilter": true
}
```

 from `capabilities.json`

**Comment by LasanthaKathriarachchi** [comment]
Oh Ok...

I can remove this part.
"selfFilter": {
"type": {
"filter": {
"selfFilter": true
}

But when I remove below part, will it stop working the filter.
filter": {
"type": {
"filter": true
}
}

I'll try once and let you know..
Thanks..

**Comment by zBritva** [comment]
@LasanthaKathriarachchi you can't use Filter API and Selection API in the same visual. 

If you need to filter data use Filter API and [call `applyJsonFilter` ](https://learn.microsoft.com/en-us/power-bi/developer/visuals/filter-api#the-advanced-filter-api)

If you need to select data point or highlight data in other visual use Selection API and [call `select` in SelectionManager](https://learn.microsoft.com/en-us/power-bi/developer/visuals/selection-api#create-selections-for-table-data-view-mapping)

The [old API `applySelectionFilter` for filtering ](https://github.com/microsoft/powerbi-visuals-api/blob/618bfc0ada71a3a9c657077d871af9dce78591b5/index.d.ts#L1236) data by using selection doesn't work in new API version of the visual. You must use old tool to build such visuals.

**Comment by LasanthaKathriarachchi** [comment]
Yes great zBritva..
Now it works as expected..
Thank you for the great help..

**Comment by LasanthaKathriarachchi** [comment]
Hi All..

I need to programmatically access the filters collection of filter panel of custom visual, at update method. If the whole filter collection is not accessible, it is enough having a boolean value true/false, to identify at-least a single filter is applied by the user, when current trigger of update method.

Can anyone advise how to access it or identify it programmatically?

Thanks in advance..
Lasantha

**Comment by zBritva** [comment]
@LasanthaKathriarachchi You can't get applied filters from visual API. 
You need to use [reportGetSlicerState of REST API](https://playground.powerbi.com/dev-sandbox?showApi=reportGetSlicerState)

**Comment by LasanthaKathriarachchi** [comment]
Hi zBritva..

Thank you for responding...
I just tried this way, but came across some doubts.

First I installed "powerbi-client" package successfully.
Then tried to apply the code parts little by little. And found these problems.

1) models = window['powerbi-client'].models;  line doesn't compile either.

2) In doubt, from where these values should come from?
    let accessToken = EMBED_ACCESS_TOKEN;
    let embedUrl = EMBED_URL;
    let embedReportId = REPORT_ID;
    let tokenType = TOKEN_TYPE;

3) When I find in elements, not elements with ID "embedContainer".
        let embedContainer = $('#embedContainer')[0];

4) Due to above reasons, couldn't create the report object.
      report = powerbi.embed(embedContainer, config);

Thanks..
Lasantha

**Comment by LasanthaKathriarachchi** [comment]
Hi Guys,

I created a tableau extension, in which I want to render a map component using pinia.
Coding done using Vue + TS + JS.

This is how I try to load the app with map in the main.js file.
--------------
main.js
--------------
import { createApp } from 'vue';
import { createPinia } from 'pinia';
import App from './App.vue';
import "./styles/general.scss";
import directives from "./directives";

const app = createApp(App);
directives(app);
const pinia = createPinia();
app.use(pinia);
app.mount('#app');
----------------------
--------------------
I'm getting this error.
--------------------
getActivePinia was called with no active Pinia. Did you forget to install pinia?
const pinia = createPinia()
app.use(pinia)
This will fail in production.
-----------------------

Please let me know, any thing more require to render the pinia map inside a tableau extension.

Thanks in advance,
Lasantha
