### ISSUE TITLE
Fetch more exception breaks code flow

### ISSUE THREAD

**Issue by KoBe321** [microsoft/PowerBI-visuals-tools#309]
With pbiviz 2.6.0:
We've got a custom visual.
In some reports, when we use the fetch more functionality with this visual,
az internal exception is thrown and the code flow is interrupted.
Also the spinner is still shown.
![b1](https://user-images.githubusercontent.com/8909363/78674836-82c44980-78e4-11ea-99d1-b4b70d6ade5e.png)
![b2](https://user-images.githubusercontent.com/8909363/78674843-8526a380-78e4-11ea-9004-457d18c97766.png)

**Comment by helen508light** [comment]
@KoBe321 
What methods from this article do you use?
https://docs.microsoft.com/en-us/power-bi/developer/visuals/fetch-more-data

Is getGradientColors your own method bound on data points from data set?

**Comment by KoBe321** [comment]
We use `host.fetchMoreData()`
No, I suspect that `getGradientColors()` is part of some PowerBi code:
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/8909363/79835509-1b5fcc80-83af-11ea-9d90-2b98682d028c.png)

**Comment by helen508light** [comment]
@KoBe321 how much data do you use?
Please note that PowerBI will presently limit the total fetched data to 100MB to avoid client memory constraints. You can detect this limit being reached when fetchMoreData() returns 'false'.

**Comment by KoBe321** [comment]
@helen508light The size of the response is 7.3 kb. I think the error is something different as it says: `t.dataColors.getRadientColors is not a function` You can check it on the screenshot I sent before.

There's a function here
https://github.com/microsoft/powerbi-visuals-utils-colorutils/blob/master/src/colorHelper.ts
which has the name getThemeColor, and seems to be similar to what breaks for us.

**Comment by Balogh1Bence** [comment]
@helen508light It happens whenever a color setting is created multiple times using the enumerateObjectInstances.
![image](https://user-images.githubusercontent.com/45355550/84748785-6108d200-afb9-11ea-9724-4797e441d8e3.png)
creating these type of settings for each columns then picking a color will create an exception during the fetchMore on powerBI side

**Comment by Balogh1Bence** [comment]
turn out picking a font color using the powerBI built-in color picker kills the fetch more

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com) with questions related to development of custom visuals
