### ISSUE TITLE
PBIVIZ not supporting for Node 13.7.0

### ISSUE THREAD

**Issue by surendrasai** [microsoft/PowerBI-visuals-tools#316]
Hi Team,

I am getting below error When I run command: 
`npm i -g powerbi-visuals-tools`

Error:
`npm WARN deprecated core-js@2.3.0: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.`

Is it issue with Node Version, or Pbiviz package?

Thanks and Regards,
Surendra.

**Comment by uve** [comment]
pbiviz supports NodeJS 12.x currently. We'll add support of 13.x later this year.
