### ISSUE TITLE
Incorrect values after using persistProperties()

### ISSUE THREAD

**Issue by KoBe321** [microsoft/PowerBI-visuals-tools#318]
I've got 2 settings, `collapsed `and `totalEnabled`.
For each of my column fields, I generate 1 of these settings.
E.g. Customer Group collapsed, Customer Name collapsed and Customer Group totalEnabled, Customer Name totalEnabled.
If the user sets `collapsed` to true, I want to set `totalEnabled` to true using `persistProperties()` for the same column.

However, after I set `totalEnabled`to true for Customer Name by code, the value of this setting is wrong in `options.dataViews[0].matrix.columns.levels` but correct in `options.dataViews[0].metadata.columns`.
See the attached picture for clarification.
![image](https://user-images.githubusercontent.com/8909363/85713732-f575e180-b6e9-11ea-84a3-05079a097c52.png)

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com) with questions related to development of custom visuals
