### ISSUE TITLE
refreshHostData not working when visual is packaged

### ISSUE THREAD

**Issue by youranupama** [microsoft/PowerBI-visuals-tools#319]
Hello Team,
We want to refresh the visual data from within the visual and tried using this.host.refresHostData()
The method call works as expected in developer mode but does not work when visual is packaged. 

Is there any requirement to make it work in the packaged visual file? 
We could not find any documentation around this feature either. Please help

**Comment by uve** [comment]
This is a privilege Custom Visuals API, please contact Power BI Custom Visuals Support <pbicvsupport@microsoft.com> to ask access to it.
