### ISSUE TITLE
Latest API redirect is not stable

### ISSUE THREAD

**Issue by intellectyxArria** [microsoft/PowerBI-visuals-tools#320]
Hello team,

            When I click on the redirect link of 3.0 article. It automatically redirects me from https://microsoft.github.io/PowerBI-visuals/docs/how-to-guide/migrating-to-powerbi-visuals-tools-3-0/ to https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals

**Comment by uve** [comment]
The migration guide is deprecated. You can find the old version here:
https://github.com/microsoft/PowerBI-visuals/blob/gh-pages/docs/how-to-guide/migrating-to-powerbi-visuals-tools-3-0.md
