### ISSUE TITLE
Incorrect (or not suitable) paddings

### ISSUE THREAD

**Issue by erapade** [microsoft/PowerBI-visuals-tools#324]
The current paddings in the R-visuals to large (40), and this needs to be reduced to 0. Microsoft has reduced this padding them-self, but for us others to find this out takes a looong time

**Comment by erapade** [comment]
This has been implemented by pullrequest https://github.com/microsoft/PowerBI-visuals-tools/pull/325. Although, I can't find any way to link this issue with a pull request (to new to github...)

**Comment by zBritva** [comment]
Hello, 

Did you try to apply sizingPolicy ?
https://www.rdocumentation.org/packages/htmlwidgets/versions/1.5.1/topics/sizingPolicy

**Comment by erapade** [comment]
> Did you try to apply sizingPolicy ?
> https://www.rdocumentation.org/packages/htmlwidgets/versions/1.5.1/topics/sizingPolicy

You need to help me out a bit here since I'm new to R
As I understand, sizingPolicy can be passed within the createWidget but not the saveWidget method. My understanding is that the widget code is generated by ggloply() method and the result is then passed to saveWidget (using internalSaveWidget)

my code:
g=ggplot(...) 
p = ggplotly(g) %>% layout(legend = list(orientation = "h", x = 0, y = 1.2))
internalSaveWidget(p, 'out.html')

**Comment by erapade** [comment]
One more comment about padding is that even if I use theme(axis.title=element_blank()) in ggplot, it doesn't look like that the space for the axis labels are released. Not sure that this is a power bi visual problem though

**Comment by Auptimum** [comment]
Been a few months, but erapade is right. `sizingPolicy` can only be passed to the `createWidget` method as detailed in this [vignette](https://cran.r-project.org/web/packages/htmlwidgets/vignettes/develop_sizing.html). I've been developing some visuals and still working through the functionality, but the extra padding added in Power BI is the first thing I want to remove when I get to the aesthetics. Would be nice if this was baked into `flatten_HTML`.
