### ISSUE TITLE
The example of static property parameters in rhtml template is wrong or confusing

### ISSUE THREAD

**Issue by erapade** [microsoft/PowerBI-visuals-tools#327]
This is the default object definition in the templates capabilities.json:
`"rcv_script": {
  "properties": {
    "provider": {
      "type": {
        "text": true
      }
    },
    "source": {
      "type": {
        "scripting": {
          "source": true
        }
      }
    }
  }
}`

And in generated settings.ts we have this (sorry for the lack of formatting, couldn't get that to work here):
`"use strict";
import { dataViewObjectsParser } from "powerbi-visuals-utils-dataviewutils";
import DataViewObjectsParser = dataViewObjectsParser.DataViewObjectsParser;
export class VisualSettings extends DataViewObjectsParser {
  public rcv_script: rcv_scriptSettings = new rcv_scriptSettings();
}
export class rcv_scriptSettings {
  public provider
  public source
}`

A smaller problem in settings.ts is that the "provider" and "source" members are implicit of the type any, it would be better to give them there true types instead. They also doesn't end with a ';'
But the real problem is the definition in capabilities.json. Although the schema allows it (and there are no schema definition in the file...), it looks like the object rcv_script is missing a displayName (although it looks like it works anyway). But then also the property objects (source and provider) are missing the desplayName attribut, and therefor we don't see these properties in the settings view in Power Bi Desktop

Please also extend the script.r file to at least read the parameters

What's written above, together with that some of the examples given (e.g. the funnel visual) are based on the old style of settings.ts makes it kind of time consuming to get a visual to work

**Comment by AleksSavelev** [comment]
Hello @erapade,

It should be fixed in the latest versions of Tools. 

Regarding the extension of the script.r file, we'll take it into our backlog, but can't give you an ETA.
