### ISSUE TITLE
Removal of the extra hovering menu in rhtml visuals

### ISSUE THREAD

**Issue by erapade** [microsoft/PowerBI-visuals-tools#331]
Using the rhtml template for creating an R custom visual you get the extra html menu in the upper part of the visual when hovering over the visual. This is never seen in any other visual and is considered by end-users as confusing.

Please provide information (preferably in the templates) how to disable this menu
![Annotation 2020-08-19 124153](https://user-images.githubusercontent.com/17324892/90625199-7d272a80-e219-11ea-856b-72163647ec80.png)

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com) with questions related to development of custom visuals

**Comment by PastorJordi** [comment]
For the record, I received similar feedback and this can be achieved directly by configuring plotly figure.
Read their documentation [here](https://plotly.com/r/configuration-options/#preventing-the-modebar-from-appearing)
