### ISSUE TITLE
How to Remove the dialog box  when I have a custom chart in Power BI Embedded? 

### ISSUE THREAD

**Issue by LawrenceTeixeira** [microsoft/PowerBI-visuals-tools#333]
Hi Everyone,

 

How can I remove this dialog box  when I have a custom chart in Power BI Embedded? We are tyying to open a extenal URL like we can do in a table in Power BI.

 
![image](https://user-images.githubusercontent.com/43327665/96032696-6ece4700-0e35-11eb-9672-cdd0ef7637cd.png)

Thanks,
Lawrence

**Comment by zBritva** [comment]
You can't. https://github.com/microsoft/PowerBI-visuals-tools/issues/289
