### ISSUE TITLE
get report title

### ISSUE THREAD

**Issue by afernandez-yseop** [microsoft/PowerBI-visuals-tools#335]
Hi

Could it be possible to have the title of the report the custom visual is on? could be a field in VisualConstructorOptions...

The use case is for the custom visual to be a little more aware of where it's running. In my particular case:
- I'd like to fill automatically some inputs as a suggestion based on the report title
- I'd like to build some external IDs by concatenating this with other strings

**Comment by AleksSavelev** [comment]
Unfortunately, Custom Visuals aren't allowed to access any information about where it's running.
