### ISSUE TITLE
Custom PowerBI Visual is showing data Even after the DataField has been removed

### ISSUE THREAD

**Issue by CoderMonish** [microsoft/PowerBI-visuals-tools#336]
![Custom Visual Stale Data](https://user-images.githubusercontent.com/73735795/97774013-810cec80-1b7a-11eb-9da0-13fbb4a806d1.PNG)
Hi Everyone,
I have created my first custom PowerBI visual using the below microsoft sample tutorial -
https://docs.microsoft.com/en-us/power-bi/developer/visuals/develop-circle-card

However, I observe that even after I remove the datafield associated with the visual, the custom visual is still showing the old/earlier data. For eg: When I add the 'Sales' field in the custom visual, it shows 340. Now when I remove it, the old data 340 is still being shown in the custom visual.

Can you please help how can this be fixed ? Does any additional code or logic required ? Or is it a bug ?
Note : When I run the 'pbiviz -V' command, it returns 3.1.15

I am posting the code inside the update function (directly taken from the tutorial provided by Microsoft in the link mentioned above) -
    public update(options: VisualUpdateOptions) {
         console.log('Visual update', options);
        let dataView: DataView = options.dataViews[0];

        
        let width: number = options.viewport.width;
        let height: number = options.viewport.height;
        this.svg.attr("width", width);
        this.svg.attr("height", height);
        let radius: number = Math.min(width, height) / 2.2;
        this.circle
            .style("fill", "white")
            .style("fill-opacity", 0.5)
            .style("stroke", "black")
            .style("stroke-width", 2)
            .attr("r", radius)
            .attr("cx", width / 2)
            .attr("cy", height / 2);
        let fontSizeValue: number = Math.min(width, height) / 5;
        this.textValue
            .text(<string>dataView.single.value) //.text("Value")
            .attr("x", "50%")
            .attr("y", "50%")
            .attr("dy", "0.35em")
            .attr("text-anchor", "middle")
            .style("font-size", fontSizeValue + "px");
        let fontSizeLabel: number = fontSizeValue / 4;
        this.textLabel
            .text(dataView.metadata.columns[0].displayName) //.text("Label")
            .attr("x", "50%")
            .attr("y", height / 2)
            .attr("dy", fontSizeValue / 1.2)
            .attr("text-anchor", "middle")
            .style("font-size", fontSizeLabel + "px");
    }

**Comment by dm-p** [comment]
Hi @CoderMonish - I've [posted a reply to your forum post about this](https://community.powerbi.com/t5/Custom-Visuals-Development/Custom-PowerBI-Visual-is-showing-data-Even-after-the-DataField/m-p/1472497/highlight/true#M3416). In short, I believe it's that your code is trying to access a non-existent `dataView` once the measure has been removed. Anything in your code that attempts to access either the `single` or `metadata` object will cause your code to silently fail and the visual DOM will remain as per the last successful update.

**Comment by CoderMonish** [comment]
Hi @dm-p,

Thank you very much for reply. I am actually stuck and do not know how to proceed next. And this being a most basic sample, I hope to get this fixed soon with your and others help.

I tried below things based on your above comments, however I still face the same issue -
1) I added the try-catch block
\2) I replaced the this.textValue & this.textLabel with optional chaining as you mentioned earlier.

Observation 1 : I observed that when I remove the 'Sales' measure, the **_last line of the try block_** is getting executed successfully. So, it seems that no exception is being thrown.

Observation 2 : I am printing the 'options' variable in the last line of the try block. When I check in the Developer console, we can see that **dataviews has data in it**. However, the ONLY change I could notice was that dataviews[0].metadata.segment is having value 'undefined'.

![DeveloperConsoleAfterRemovingMeasure](https://user-images.githubusercontent.com/73735795/98108360-d4a47080-1ec1-11eb-88c4-b91cf17d6306.PNG)

Do you want me to share the visual.ts file with you ? Can you try reproducing the issue at your end, since I am using the basic code provided in the Microsoft tutorial itself.

Thank you once again for your help.

High-level changes are as mentioned below -
public update(options: VisualUpdateOptions) {
          try {
                //code for re-drawing the visual
               // . . . 
              this.textValue
                    .text(<string>dataView?.single?.value ?? "(blank)")
              // some more code . . .
             this.textLabel
                   .text(dataView?.metadata?.columns?.[0]?.displayName ?? "[No Measure]")
            //some more code . . . 

        console.log('Visual update', options);
        console.log('I reached end of try block !!')
}

**Comment by mkennecke** [comment]
Hi guys,

is there any update regarding this issue? I have noticed the same behavior and for me it seems to be wrong.

Thanks!

**Comment by AleksSavelev** [comment]
The issue seems to be resolved on the [community forum](https://community.fabric.microsoft.com/t5/Custom-Visuals-Development/Custom-PowerBI-Visual-is-showing-data-Even-after-the-DataField/m-p/1472497/highlight/true#M3416)
