### ISSUE TITLE
Sorting using capabilies.json not working 

### ISSUE THREAD

**Issue by krngd2** [microsoft/PowerBI-visuals-tools#338]
According to [this article ](https://docs.microsoft.com/en-us/power-bi/developer/visuals/sort-options)

```
 "sorting": {
        "default": {   }
    }
```
Should produce result something like this 
![image](https://user-images.githubusercontent.com/10483437/98563853-ac59af00-22d1-11eb-802d-dc77efb6fd8e.png)

It is not working at all,
![image](https://user-images.githubusercontent.com/10483437/98564006-d7dc9980-22d1-11eb-8732-2648c3f25acb.png)

I tried sorting with 
```
    "sorting": {
        "implicit": {
            "clauses": [
                {
                    "role": "category",
                    "direction": 1
                },
                {
                    "role": "measure",
                    "direction": 2
                }
            ]
        }
```
This also does not work at all

Am I missing something or is this a bug. Please clarify.

**Comment by helen508light** [comment]
@krngd2
It do works for https://github.com/microsoft/powerbi-visuals-gantt for example
Could you please provide you capabilities.json? Maybe you have some issues with DataViewMapping usage in general
