### ISSUE TITLE
tsconfig.json exclude give TypeError

### ISSUE THREAD

**Issue by Mcburn** [Microsoft/PowerBI-visuals-tools#34]
i got this error when add the exclude or include feature from typescript 2.0. Also when i delete the files array.

Here is a sample code from my tsconfig.ts:

`{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "outFile": "../../built/local/tsc.js",
        "sourceMap": true
    },
    "exclude": [
        "node_modules",
        "wwwroot"
    ]
}`

Here is the complete Error Stack Trace:

`info   Building visual...
 error  UNKNOWN TypeError: Cannot read property 'filter' of undefined
    at e (C:\Users\X180538\AppData\Roaming\npm\node_modules\powerbi-visuals-tool
s\lib\VisualBuilder.js:164:45)
    at VisualBuilder._validateApiVersion (C:\Users\X180538\AppData\Roaming\npm\n
ode_modules\powerbi-visuals-tools\lib\VisualBuilder.js:145:16)
    at VisualBuilder.build (C:\Users\X180538\AppData\Roaming\npm\node_modules\po
werbi-visuals-tools\lib\VisualBuilder.js:91:21)
    at VisualPackage.loadVisualPackage.then (C:\Users\X180538\AppData\Roaming\np
m\node_modules\powerbi-visuals-tools\bin\pbiviz-package.js:55:13)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3`

Sam from the Power BI Developer Forum give me a hint to this line of code:
code in powerbi-visuals-tools\lib\VisualBuilder.js,
`let apiDtsFiles = tsConfig.files.filter(i => i.match(/.api\/.+\/PowerBI-visuals.d.ts$/));`

**Comment by raananzvi** [comment]
Hi,

Are you sure the two things are related? I just created a new empty visual with the CLI tools, added the exclude property to the tsconfig.json file:
`{
  "compilerOptions": {
    "allowJs": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "ES5",
    "sourceMap": true,
    "out": "./.tmp/build/visual.js"
  },
  "files": [
    ".api/v1.1.0/PowerBI-visuals.d.ts",
    "src/visual.ts"
  ],
  "exclude": [
    "node_modules", "wwwroot"
  ]
}`

And the packaging worked fine.
Try to validate that you are running the package command from the right folder (you should run it from the root folder of your visual)

**Comment by Mcburn** [comment]
Hey Raananzvi,

as mentioned here: http://www.typescriptlang.org/docs/handbook/tsconfig-json.html
I can use the exclude and include feature without the files feature.

When i add the files array to the tsconfig pbiviz is building my package. But it ignore my include or exclude array.

Typescript 2.0 is very young, so maybe pbiviz do not supported yet?

**Comment by raananzvi** [comment]
After further looking at the code, your hint was correct, our command line tool is trying to validate that you are building the correct PowerBI-visuals.d.ts file (from the correct API version).
The best workaround for now is to keep the files list with the line for PowerBI-visuals.d.ts file and exclude the ".api" folder. This will make sure you get what you want and keep the toolset happy.

We can try and mitigate this issue in future releases, but I'm not sure if we can do this easily.

**Comment by Mcburn** [comment]
I will try this out. 
In the moment i get the feeling i really understand the pbiviz environment.

So iám happy i can help you to improve powerbi-visual-tools. 

Thank you very much for your answer and your time.
