### ISSUE TITLE
SelectionId on a table column with distinct values

### ISSUE THREAD

**Issue by hzakeri** [microsoft/PowerBI-visuals-tools#340]
Hello,
I want to define selectionId on a table column. The column includes some different value which may duplicate, but I want to have a selectionId for distinct values. I used this code but it didn't work. In my example table, I have 41 rows and 3 columns. In column 2, I have only 9 distinct values, and I want to create selectionIds only for this values. How can I do that? 

  public getSelectionIds(dataView: DataView, host: IVisualHost): ISelectionId[] {
       return  dataView.table.identity.map((identity: DataViewScopeIdentity) => {
            const categoryColumn: DataViewCategoryColumn = {
                source: dataView.table.columns[0],
                values: null,
                identity: [identity]
            }
                return host.createSelectionIdBuilder()
                .withCategory(categoryColumn, 0)
                .createSelectionId();
      });
    }
Thank you in advance for your help

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com) with questions related to development of custom visuals
