### ISSUE TITLE
Give provision for report page navigations using custom visuals without using buttons

### ISSUE THREAD

**Issue by VarunMKroger** [microsoft/PowerBI-visuals-tools#346]
In PBI there is a provision to add page navigation on a button to navigate from one page to another page in a report. Is there a provision to achieve the same from a custom visual through formatting interface without using existing PBI buttons? 
If not would please plan to add this feature.

**Comment by helen508light** [comment]
@VarunMKroger
now there is no such possibility.
We'll add it to backlog
