### ISSUE TITLE
Broken links to custom visuals documentation on github

### ISSUE THREAD

**Issue by Aorus42** [microsoft/PowerBI-visuals-tools#347]
I began working through the [RVisualTutorial ](https://github.com/Microsoft/PowerBI-visuals/tree/master/RVisualTutorial/TutorialFunnelPlot) last December, but have been unable to access it again since early January. Several links are now broken that previously pointed to github documentation on building custom visuals in R.

Does anyone know what happened and whether the documentation is still available somewhere?

Thank you!

**Comment by zBritva** [comment]
@Aorus42 https://docs.microsoft.com/en-us/power-bi/developer/visuals/funnel-plot-from-r - is it the same?

**Comment by Aorus42** [comment]
@zBritva definitely helpful, thank you! I found a link in there that goes to the original tutorial I had found; it looks like someone forked it here: https://github.com/PowerBi-Projects/PowerBI-visuals/blob/master/RVisualTutorial/
