### ISSUE TITLE
fetch more does not work in a certaion scenario

### ISSUE THREAD

**Issue by Balogh1Bence** [microsoft/PowerBI-visuals-tools#348]
It only happens when there is only one segment missing from the data.

- load a report with visual that can use the fetch more feature
- use the fetch more on the visual
- enter in edit mode
- change back to reading view

when changing back, the update sent on changing reading view contains the data that was originally loaded before using the fetch more. It also contains a segment object, meaning that fetch more can be called to get more data. Using fetch more now does not load any more data, even though the powerbi sent a segment object.

 Calling fetch more does nothing at all, but returns with true.

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com) with questions related to development of custom visuals
