### ISSUE TITLE
Internet access from a Custom R Visual in Power BI Service

### ISSUE THREAD

**Issue by lucazav** [microsoft/PowerBI-visuals-tools#350]
Is it possible to access to a web service endpoint from a Custom R Visual, even if I use it in Power BI Service?

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com (mailto:pbicvsupport@microsoft.com) with questions related to development of custom visuals
