### ISSUE TITLE
Access user principle

### ISSUE THREAD

**Issue by JipAccobat** [microsoft/PowerBI-visuals-tools#354]
Hello,

Is it possible to access user principle (john.doe@example.com) form inside the visual?
Or is there any type of AAD integration that can be accessed from the visual?

I have tried using the IAuthenticationService but is met with an status 400 or 401.
I have also tried window.powerbi.session.UserInfoUtils but it seems to be empty.

**Comment by uve** [comment]
users info is not available due to privacy aspects
