### ISSUE TITLE
Conditional formatting not supported for Table based visuals

### ISSUE THREAD

**Issue by djpirra** [microsoft/PowerBI-visuals-tools#360]
Hi,

I have built a custom visual that uses the Table dataviewmapping, just to realize that apparently it does not support conditional formatting.
Currently my dataview mapping consists on the following config:

```json
"table": {
            "rows": {"select": [
                {
                    "for": {
                        "in": "main"
                    }
                },
                {
                    "bind": {
                        "to": "other"
                    }
                },
                {
                    "bind": {
                        "to": "target"
                    }
                }
            ]
            }
        }
```

Would we have an equivalent setting that would allow supporting conditional formatting?

Thank you

**Comment by krngd2** [comment]
I am using matrix data view mapping. Its seems like its not supporting with matrix data view mapping too. 

https://community.powerbi.com/t5/Developer/Custom-visuals-How-to-access-colors-set-in-Conditional/m-p/1900132#M29983

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact pbicvsupport@microsoft.com with questions related to development of custom visuals

Conditional formatting now should be available for all custom visuals.
