### ISSUE TITLE
unable to install pbiviz

### ISSUE THREAD

**Issue by mathlieu** [microsoft/PowerBI-visuals-tools#368]
I don't know what I"m doing wrong. Can anyone help?

End of the log:
16225 verbose stack Error: powerbi-visuals-tools@3.2.0 preinstall: `npx npm-force-resolutions`
16225 verbose stack Exit status 1
16225 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
16225 verbose stack     at EventEmitter.emit (events.js:376:20)
16225 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
16225 verbose stack     at ChildProcess.emit (events.js:376:20)
16225 verbose stack     at maybeClose (internal/child_process.js:1055:16)
16225 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
16226 verbose pkgid powerbi-visuals-tools@3.2.0
16227 verbose cwd C:\WINDOWS\system32
16228 verbose Windows_NT 10.0.19042
16229 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "powerbi-visuals-tools"
16230 verbose node v14.17.0
16231 verbose npm  v6.14.13
16232 error code ELIFECYCLE
16233 error errno 1
16234 error powerbi-visuals-tools@3.2.0 preinstall: `npx npm-force-resolutions`
16234 error Exit status 1
16235 error Failed at the powerbi-visuals-tools@3.2.0 preinstall script.
16235 error This is probably not a problem with npm. There is likely additional logging output above.
16236 verbose exit [ 1, true ]

**Comment by dawaldow** [comment]
I am getting the same error today...

**Comment by dawaldow** [comment]
I was able to install the 3.1.19 version, so not sure what is going on with the 3.2.0 build.  That is above my pay grade.

**Comment by mathlieu** [comment]
me too I 've been able to install 3.1.19. thx @dawaldow

**Comment by JipAccobat** [comment]
I'm facing the same problem with installing version 3.2.0

**Comment by WillAyd** [comment]
I was getting the same issue on macOS, though the error manifested itself as `Error: ENOENT: no such file or directory, open './package-lock.json'`

**Comment by novasilva-admin** [comment]
I am getting this same issue when installing version 3.2.0.
I am able to install 3.1.19, but this version has vulnerabilities.

**Comment by AlanGroskreutz** [comment]
So how would one install 3.1.19?  All I know to do is run `npm i -g powerbi-visuals-tools`

**Comment by JipAccobat** [comment]
@AlanGroskreutz use `npm i -g powerbi-visuals-tools@3.1.19`

**Comment by uve** [comment]
We'll fix the issue in the upcoming version of tools.

**Comment by JipAccobat** [comment]
@uve version 3.2.1 wont install the same error as 3.2.0 and version 3.2.2 is not available for download.

**Comment by Demonkratiy** [comment]
This issue is fixed in release version 3.2.3 which is now available for download.

**Comment by JipAccobat** [comment]
I can confirm that I'm able to install version 3.2.3.
