### ISSUE TITLE
Visual that works locally doesn't work when packaged as a pbiviz

### ISSUE THREAD

**Issue by jonbgallant** [Microsoft/PowerBI-visuals-tools#37]
This visual: https://github.com/jonbgallant/powerbi-visuals-liquidfillgauge...works when deving locally via localhost, but doesn't work when package and import as pbiviz.

Looks like an iframe is used with pbiviz but local does not.

Here's the pbiviz that doesn't work: https://github.com/jonbgallant/PowerBI-visuals-liquidFillGauge/tree/master/liquidFillGauge/dist

I could fix via in code, but a visual that works on local should work as pbiviz regardless of the code that is in the visual.

**Comment by raananzvi** [comment]
The debug visual is going to also be hosted inside an IFRAME in the near future. Please make sure your visuals are working in an IFRAME.
You can use the command "pbiviz package --no-minify" to package your visual with unminified code so you will be able to debug it.
