### ISSUE TITLE
Upgrade `powerbi-visuals-api` to latest version

### ISSUE THREAD

**Issue by iMicknl** [microsoft/PowerBI-visuals-tools#375]
While using `pbiviz`, I noticed that the version of `powerbi-visuals-ap` is set to ^2.6.2 automatically. If I manually upgrade the version to 3.8.2 (latest), running pbiviz will downgrade it to 2.6.2 automatically.

Is there a specific reason why an older version (a year old) is pinned? And is there a way to upgrade this version, without being dependent from an update of the tools.

**Comment by dmitryvorono** [comment]
Hello!
In the `pbiviz.json` increase the `apiVersion` to 3.8.2 too. It helped me.

**Comment by iMicknl** [comment]
Thanks @dmitryvorono, I will give it a try! Do you know if this is documented somewhere, otherwise I will leave this issue open for tracking purposes.

**Comment by iMicknl** [comment]
@dmitryvorono seems that it is not possible to increate the `apiVersion` with `pbiviz` 3.2.3.

```error  VALIDATION   Invalid API Version v3.8.2````

``` error  VALIDATION   Invalid API Version v3.8.0```

**Comment by uve** [comment]
set API 3.8.0 in pbiviz.json file and run the following command:
npm i --save powerbi-visuals-api@3.8.0

**Comment by iMicknl** [comment]
Thanks @uve, it seems to work. Running `pbiviz start` the first time was a bit flaky, but a second time it worked without issues.

For example:

![image](https://user-images.githubusercontent.com/1424596/122833841-e8380680-d2ed-11eb-9694-6a7624497ad0.png)

and 

![image](https://user-images.githubusercontent.com/1424596/122833871-f1c16e80-d2ed-11eb-8f93-89d3b4ce2062.png).

However, the above workaround is sufficient so I will close this issue.
