### ISSUE TITLE
Custom Visual actions - Set bookmark, Page Navigation and setting parameter

### ISSUE THREAD

**Issue by VijaySyntech** [microsoft/PowerBI-visuals-tools#378]
Hi Team,

Can you please let us know if any of the below is possible via custom visuals?
Select bookmark
Page Navigation 
setting parameter

If not, when you are planning to bring this functionality. 

I believe that these are the basic needs for any custom visual developer to bring some useful actions.
I see these are available in other BI tools like Qlik. But sad to see it is not available in Power BI custom visual API yet.
We are losing customers with no such features via API.

Any help to prioritize this is much appreciated.

**Comment by dm-p** [comment]
Not from the team, but can confirm it's not currently possible. Can also confirm I'd like these features too though :)

**Comment by JoshMayberry** [comment]
I am also interested in these features.

**Comment by powerviz** [comment]
@blackleaden when we can expect this to be resolved?
This is 2 years since we raised the issue.

**Comment by AleksSavelev** [comment]
Hello everyone! @powerviz @VijaySyntech @dm-p @JoshMayberry 
I started looking into all the open issues in tools and utils recently, sorry for such a big delay.

You can add bookmark support to your custom visual. Please, follow [this guide](https://learn.microsoft.com/en-us/power-bi/developer/visuals/bookmarks-support).

Please describe what you meant by "Page Navigation" and "setting parameter"? Also, I'm not sure what "Qlik" means.

**Comment by dm-p** [comment]
Hi @AleksSavelev - unfortunately the link is not what we're asking for with respect to bookmarks. We would like to be able to access bookmarks in the report and select them, not ensure that bookmark state can be restored (which has been available for a while).

The easiest comparison would be something like [the bookmark and/or page navigator core visual](https://learn.microsoft.com/en-us/power-bi/create-reports/button-navigators?tabs=powerbi-desktop) - these can list bookmarks or pages from the report and allow a user to control navigation. This core visual is incredibly useful, but very limited and there is a lot of potential within custom visuals to improve these experiences for users, if APIs are made available effort us to do so. This should hopefully clear yp tour questions on the concept of page navigation also.

Qlik is a product in the same space as Power BI that offers superior functionality in this area for report authors. As developers, ot would be great for us to be able to offer opportunities to users to enhance these experiences in Power BI where the core visuals fall short.

**Comment by powerviz** [comment]
Hi @AleksSavelev  Daniel is right. We definitely need this Bookmark/Page Navigator. 
https://learn.microsoft.com/en-us/power-bi/create-reports/button-navigators?tabs=powerbi-desktop
if you can give us the API to do so from Custom visual, this will be the best thing ever happen to custom visuals. To be honest, we didn't see any major features released to PowerBI custom visuals lately.  Would appreciate, if you can help here.

**Comment by AleksSavelev** [comment]
I got your point. Unfortunately, I can't help you with it, but it looks like a good feature. You should suggest an idea on the powerbi forum. Here is the [link to the forum](https://community.powerbi.com/t5/Custom-Visuals-Ideas/idb-p/CustomVisualsIdeas) with ideas for Custom Visuals. PowerBI team always reviews these suggestions.

**Comment by SirCypkowskyy** [comment]
I believe that the introduction of such a feature would be a very positive change in the Power BI environment, and could lead to a visual and functional enhancement of many reports.

I don't understand why Microsoft has avoided introducing such a solution to date, especially given that the native slicers and buttons seem to be obsolete in some regards.

**Comment by FelipeCostaGualberto** [comment]
I created this idea, vote if you find it useful: [https://community.fabric.microsoft.com/t5/Custom-Visuals-Ideas/Expose-API-for-Custom-Visuals-to-List-and-Trigger-Bookmarks/idi-p/4219984#M1668](https://community.fabric.microsoft.com/t5/Custom-Visuals-Ideas/Expose-API-for-Custom-Visuals-to-List-and-Trigger-Bookmarks/idi-p/4219984#M1668)
