### ISSUE TITLE
Modal dialog box issue

### ISSUE THREAD

**Issue by VijaySyntech** [microsoft/PowerBI-visuals-tools#384]
Hi team,
I am using the modal dialog box. However, i see the below message that always stays with the dialog box.
It is not a good user experience.

if the user always want to allow dialog box from a specific custom visual, is there a setting to do?
or else, if the user adds the visual under organization visuals, will this stop coming ?

Any help here is appreciated.

![image](https://user-images.githubusercontent.com/86834273/126403831-c025a8ed-f612-4e74-ae37-1d962104d330.png)

**Comment by AleksSavelev** [comment]
Unfortunately, it is not possible to hide this checkbox. See the [documentation](https://learn.microsoft.com/en-us/power-bi/developer/visuals/create-display-dialog-box#dont-show-dialog-box)
