### ISSUE TITLE
Move from TSLint to ESLint

### ISSUE THREAD

**Issue by iMicknl** [microsoft/PowerBI-visuals-tools#385]
⚠️ TSLint is deprecated. It would make sense to migrate this integration (and requirements for visual certification) to ESLint.

See https://github.com/palantir/tslint.

**Comment by JipAccobat** [comment]
@iMicknl you can use their beta version of [ESLint library](https://www.npmjs.com/package/eslint-plugin-powerbi-visuals) if you want to change to manually.

However TSLint is still a part of their [Certification process](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-certified).

**Comment by iMicknl** [comment]
Thanks @JipAccobat! My note was for the certification process as well, I don't want to use ESLint for development and move back to TSLint for certification.

**Comment by AleksSavelev** [comment]
Eslint is required for certification now

**Comment by iMicknl** [comment]
@AleksSavelev is it correct that the new ESLint config (https://github.com/microsoft/PowerBI-visuals-tools/blob/main/.eslintrc.json) is very different compared to the old TSLint config?

Is it expected for Power BI visuals to adhere fully to https://github.com/microsoft/PowerBI-visuals-tools/blob/main/.eslintrc.json?

**Comment by AleksSavelev** [comment]
Hi @iMicknl, [this config](https://github.com/microsoft/PowerBI-visuals-tools/blob/main/.eslintrc.json) is used only in tools, not in the custom visuals. 
You're right, we have [eslint plugin](https://github.com/microsoft/eslint-plugin-powerbi-visuals) with all the required rules.
So, the eslintrc file should look similar to this one
![image](https://user-images.githubusercontent.com/94454577/236803716-25f4b9e1-f9e0-4565-bd46-9094acc5c6c7.png)
