### ISSUE TITLE
Always Invalid certificate after pbiviz start

### ISSUE THREAD

**Issue by spreusler** [microsoft/PowerBI-visuals-tools#388]
Hi PBI Team,

I am not sure how it appeared, but `pbiviz start` **always** wants to create a new certificate, because the old one is invalid.

![grafik](https://user-images.githubusercontent.com/13004206/128367488-cd6e33ae-4098-4255-9d81-0306e36373b1.png)

Therefore I always have to visit the following adress in order to authorize my browser to use this address:
https://localhost:8080/assets/status

This problem only appears once after the first compiler run. When I change something in the running visual project, the project recompiles again with **no** certificate error.

**Comment by Demonkratiy** [comment]
Hello, 
there was a bug with certificate verification for some locale regions. 
We just released tools version 4.0.0 where this issue should be fixed, please try to use it.

**Comment by phume03** [comment]
The issue persists on pbiviz 4.1.0, on Linux. Certificates generated by openssl are deemed invalid, thus the visuals cannot be started.
