### ISSUE TITLE
Visualization goes "Blank" after Resize

### ISSUE THREAD

**Issue by wzorn** [microsoft/PowerBI-visuals-tools#389]
I'm experiencing a strange behavior while trying to develop a custom visual.
 
The visualization goes blank after resizing the visualization.  

I've reverted to the default template created during "pbiviz new" and see the same behavior.  It looks like the div id="sandbox-host" is completely wiped.  Update count works if you just add and remove a data field, but as soon as you resize the visualization, the entire visual goes blank.

EDIT:  I noticed that the visualization doesn't go "blank" until the mouse-up on the resize.  The Update counter continues to increment after the frame has been grabbed and resized.  When the mouse button is released is when the visualization goes blank.

I'm not sure what could be causing this.  This was working a few day sago.  Did something change?  Is it possible I have something that's conflicting?  I thought that creating a new visualization package would remove that element, but the problem is still there.  Any thoughts on how to debug this?

Example DOM before resize:

- <iframe class="visual-sandbox" sandbox="allow-scripts" name="visual-sandbox" width="270" height="270" src="https://app.powerbi.com/13.0.16512.57/cvSandboxMinimal.html?=&amp;plugin=defaultNew1A8845E7A9D742D3BCDBFEB182A03F2D_DEBUG&amp;locale=en-US" style="width: 270px; height: 270px;">
- 	<html>
- 		<head>...</head>
- 		<body class="visual-sandbox">
- 			<div id="sandbox-host" class="visual visual-defaultNew1A8845E7A9D742D3BCDBFEB182A03F2D_DEBUG">
- 				<p>
- 					Update count:
- 					<em>7</em>
- 				</p>
- 			</div>
- 			<script>
- 				var powerbi = {
- 					common: {}
- 				};
- 			</script>
- 			<script type="text/javascript" src="./scripts/visualsandbox.minimal.externals.min.js"></script>
- 			<script type="text/javascript" src="./scripts/customVisualsHost.bundle.min.js"></script>
- 			<script>...</script>
- 			<script id="js-defaultNew1A8845E7A9D742D3BCDBFEB182A03F2D_DEBUG" name="defaultNew1A8845E7A9D742D3BCDBFEB182A03F2D_DEBUG>...</script>
- 		</body>
- 	</html>
- </iframe>

DOM after resize:

- <iframe class="visual-sandbox" sandbox="allow-scripts" name="visual-sandbox" width="270" height="270" src="https://app.powerbi.com/13.0.16512.57/cvSandboxMinimal.html?=&amp;plugin=defaultNew1A8845E7A9D742D3BCDBFEB182A03F2D_DEBUG&amp;locale=en-US" style="width: 270px; height: 270px;">
-  	<html>
-  		<head>...</head>
-  		<body class="visual-sandbox">
-  			<div id="sandbox-host" class="visual"></div>
-  			<script>
-  				var powerbi = {
-  					common: {}
-  				};
-  			</script>
-  			<script type="text/javascript" src="./scripts/visualsandbox.minimal.externals.min.js"></script>
-  			<script type="text/javascript" src="./scripts/customVisualsHost.bundle.min.js"></script>
-  			<script>...</script>
-  			<script id="js-defaultNew1A8845E7A9D742D3BCDBFEB182A03F2D_DEBUG" name="defaultNew1A8845E7A9D742D3BCDBFEB182A03F2D_DEBUG>...</script>
-  		</body>
-  	</html>
-  </iframe>

**Comment by AleksSavelev** [comment]
I wasn't able to reproduce it on my end. Let me know if this issue still appears
