### ISSUE TITLE
Get selected item after filtering using context menu 

### ISSUE THREAD

**Issue by lucmax94** [microsoft/PowerBI-visuals-tools#392]
Hi,

is there a way to get information about the selection that gets created when including/excluding a datapoint using a context menu?

We have a custom visual and need to know, if the user included/excluded a datapoint using the context menu so we can show a button to reset this selection. Just calling selectionManager.clear() method isn't clearing the selection.

Best regards
lucmax

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com) with questions related to the development of custom visuals
