### ISSUE TITLE
openModalDialog does not always show content

### ISSUE THREAD

**Issue by Balogh1Bence** [microsoft/PowerBI-visuals-tools#394]
I have created a custom visual that implements the dialog found in this tutorial:
https://docs.microsoft.com/en-us/power-bi/developer/visuals/create-display-dialog-box?tabs=JavaScript#add-your-dialog-box-to-the-registry-list

When I open the dialog using host.openModalDialog, it appears, but the content is not always added. 
Also there is a huge delay between the time the dialog appears and the content of the dialog appears.

This is the definition of the dialog:
![image](https://user-images.githubusercontent.com/45355550/133422041-090b1509-e316-4088-95ac-aefebbb0f83c.png)

This is how I open it: 
![image](https://user-images.githubusercontent.com/45355550/133422115-a9c2ecc5-baff-4831-8e45-ffc158a59e20.png)

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com) with questions related to the development of custom visuals
