### ISSUE TITLE
persistProperties does not trigger update using empty dataview

### ISSUE THREAD

**Issue by Balogh1Bence** [microsoft/PowerBI-visuals-tools#396]
I have implemented the supportsEmptyDataView feature, but using host.persistProperties does not trigger update.

Looks like im not the only one facing this issue: https://community.powerbi.com/t5/Developer/persistProperties-with-empty-dataview/m-p/1862518/thread-id/29578/highlight/true

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com) with questions related to the development of custom visuals
