### ISSUE TITLE
Analytics pane should work similar to the format pane, but it does not

### ISSUE THREAD

**Issue by LingVuDev** [microsoft/PowerBI-visuals-tools#398]
I wanted to develop a pbi visual having some `objects` in the analytics pane instead of the format pane, but there are actually some really significant differences which are not documented in the PowerBI visuals developer documentation.

https://docs.microsoft.com/en-us/power-bi/developer/visuals/analytics-pane
> You can define other properties in the same way that you do for Format objects. And you can enumerate objects just as you do in the Format pane.

objects of my `capabilities.json`:
```json
 "objects": {
    "apiSettings": {
      "displayName": "API Settings",
      "objectCategory": 2,
      "properties": {
        "apiUrl": {
          "displayName": "API URL",
          "type": { "text": true }
        },
        "apiToken": {
          "displayName": "API Token",
          "type": { "text": true }
        }
      }
    }
  },
```

enumerateObjectInstances from `visual.ts`
```ts
  public enumerateObjectInstances(options: EnumerateVisualObjectInstancesOptions): VisualObjectInstanceEnumeration {
    let objectName = options.objectName;
    let objectEnumeration: VisualObjectInstance[] = [];

    if (!defaultSettings) {
      return objectEnumeration;
    }

    objectEnumeration.push({
      objectName,
      properties: {
        apiUrl: 'test',
        apiToken: 'testToken',
      },
      selector: null,
    });

    return objectEnumeration;
  }
```
Some code snippets was taken from https://github.com/microsoft/PowerBI-visuals-sampleBarChart

1. There is this `+ Add` button, which does nothing in this case. This is not defined in the capabilites at all. On top the objects are disabled.
<img width="182" alt="Screenshot 2021-10-15 at 12 44 08" src="https://user-images.githubusercontent.com/30183724/137475776-3b1ec008-5110-469f-b771-d7ca273ec442.png">

2. Clicking on the `+ Add` button makes the form fields disappear for some reason.
<img width="185" alt="Screenshot 2021-10-15 at 12 51 26" src="https://user-images.githubusercontent.com/30183724/137476166-d8a2460d-a3a2-4554-a80b-67fb088dfbc1.png">

3. The workflow is quite different from the format pane, even though the capabilities.json doesn't change besides the `objectCategory`. In the format pane I can just type in the value as expected. 

<img width="179" alt="Screenshot 2021-10-15 at 15 13 57" src="https://user-images.githubusercontent.com/30183724/137492692-60c9a23c-ba45-48a2-9322-afeac90cad6b.png">

My question: How can I use the analytics pane in the same way like the format pane?

Hope you can answer my questions.

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com) with questions related to the development of custom visuals
