### ISSUE TITLE
Visual update doesn't fire when switching from reading to edit view

### ISSUE THREAD

**Issue by tarockx** [microsoft/PowerBI-visuals-tools#401]
I'm developing a custom visual where I need to detect if the report is in reading view or edit view, since I want to show a different button depending on the current View Mode.

According to the method documentation, when the view mode changes the visual's `update()` method should get called, with the value of the `options.type` parameter set to `powerbi.VisualUpdateType.ViewMode`

However, from my tests this only happens when switching from edit to view mode. When switching from view to edit mode, the `update()` method is not called.

Is this a bug in the PowerBI service/api? Here's a snippet of the `update()` method of my visual for reference:

```
public update(options: VisualUpdateOptions) {
	if (powerbi.VisualUpdateType.ViewMode === (options.type & powerbi.VisualUpdateType.ViewMode) ) {
		//we never get here when switching from reading view to edit view 
		//it only works when switching from edit view to reading view
	}
}
```

**Comment by AleksSavelev** [comment]
To detect if the visual in the edit or reading mode use `viewMode` property in the update options.
``` typescript
 update(options){
     const isEditMode = Boolean(options.viewMode)
     ...
 }
```
`viewMode` option has two possible values:
- 0 (reading mode)
- 1 (edit mode)

**Comment by tarockx** [comment]
> To detect if the visual is in the edit or reading mode use `viewMode` property in the update options.
> 
> ```ts
>  update(options){
>      const isEditMode = Boolean(options.viewMode)
>      ...
>  }
> ```
> 
> `viewMode` option has two possible values:
> 
> * 0 (reading mode)
> * 1 (edit mode)

Thanks for your reply. 
Note that the issue I was having at the time was that the `update` method **didn't get called at all** when switching from reading to edit mode, so I had no way to be notified when the change occurred. So not really an issue of "how to read the information", it was an issue of "I had no way to know the information had changed".

I say "was" because I just checked and the issue seems to be gone, so probably a server-side fix or API update resolved it sometimes in the last 2 years, works correctly now.
