### ISSUE TITLE
Color palette gives same colors for different values

### ISSUE THREAD

**Issue by Melethainiel** [microsoft/PowerBI-visuals-tools#406]
I'm working on a custom visual which display colored svg shapes based on data and user selection

Here is the part to generate the colors by values.
```ts
for (let index = 0; index < viewModel.Forms.length; index++) {
    const element = viewModel.Forms[index];
    let value = element.ConcactValue;
    let color = this.host.colorPalette.getColor(value).value;
    element.Color = color;
    console.log({value, color});
}
```
And here is the result:
![image](https://user-images.githubusercontent.com/19528813/146041003-45c30422-932a-4a0f-8af0-1a26098b74c5.png)

and if I change the value with more color here is the bug;
![image](https://user-images.githubusercontent.com/19528813/146040970-b4a0fb47-a856-400e-b7f6-93bf84f6adc1.png)

I opened the console and print the tuples for each pair.
For the first refresh, it's all good :
```json
[
  {"value": "#NA", "color": "#118DFF",}
  {"value": "#NA", "color": "#118DFF"},
  {"value": "attentes EF/EU seront mises en œuvre à proximité des sanitaires", "color": "#12239E"},
  {"value": "Sans objet", "color": "#E66C37"},
  {"value": "Sans objet", "color": "#E66C37"},
]
```
but when data are updated, I got this:
```json
[
  {"value": "#NC", "color": "#118DFF"},
  {"value": "Attentes EU/EF", "color": "#12239E"},
  {"value": "#NA", "color": "#118DFF"},
  {"value": "#NA", "color": "#118DFF"},
  {"value": "#NA", "color": "#118DFF"},
  {"value": "#NA", "color": "#118DFF"},
  {"value": "Sans objet", "color": "#E66C37"},
  {"value": "Sans objet", "color": "#E66C37"},
  {"value": "#NA", "color": "#118DFF"},
  {"value": "Sans objet", "color": "#E66C37"},
  {"value": "Un robinet de puisage / Un siphon de sol PVC", "color": "#E66C37"},
  {"value": "#NC", "color": "#118DFF"},
  {"value": "#NC", "color": "#118DFF"},
  {"value": "#NA", "color": "#118DFF"},
  {"value": "#NC", "color": "#118DFF"}
]
```

As you can see, the color #118DFF is given for #NC and #NA.

However, the bug append, only if the new dataset is bigger than the previous (5 values to 15 will have the bug but 15 to 5 will be good).
I tried with the `this.host.colorPalette.reset()` but nothing changed.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/19528813/146045273-84b9f330-ed54-4bd6-8a62-9f863f440525.gif)

The full source code is [here](https://github.com/Melethainiel/pbiSvgDrawer)
And here is a sample of the data binding into the visual
![image](https://user-images.githubusercontent.com/19528813/146046035-81c5bccc-6db7-4b75-ad2f-816acda92932.png)

Sorry if it's not a bug, but me who uses the library badly (and for my english)

**Comment by AleksSavelev** [comment]
It was a bug in PowerBI, but it should be fixed now. Let me know if you still facing this issue.
