### ISSUE TITLE
Provide access to default tooltip formatting options

### ISSUE THREAD

**Issue by ajtech9** [microsoft/PowerBI-visuals-tools#407]
Please provide the ability to access Tooltip formatting options values - Type (Default/Report page), color, font-size and other text formatting options in custom visuals. So that it makes more benefit for a custom visual developer to handle personalization's in the tooltip canvas.

![image](https://user-images.githubusercontent.com/74089136/147927538-97e35472-9ddf-4733-b4d4-414b62a6976e.png)

**Comment by spandl** [comment]
I would like to add another point here:

The API should return if tooltips are enabled or not.

ITooltipService.enabled() returns true as soon as tooltips are enabled in the capabilities settings

```
interface ITooltipService {
        enabled(): boolean;
        show(options: TooltipShowOptions): void;
        move(options: TooltipMoveOptions): void;
        hide(options: TooltipHideOptions): void;
    }
```

It is however, much more important to find out if a use had disabled the tooltips in the style panel.
If tooltips are disabled (and cross filtering not possible) the cursor should not change when a user is rolling over active elements of the chart.

Enabled tooltips should result in a `pointer` cursor. Not knowing if tooltips are enabled or not will result in poorer UX.

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. I would suggest you create a feature request on [PowerBI Forum](https://community.fabric.microsoft.com/t5/Developer/bd-p/Developer).
