### ISSUE TITLE
4.1.0 Matrix Expand Collapse not working in packaged version

### ISSUE THREAD

**Issue by vicktor3** [microsoft/PowerBI-visuals-tools#410]
I created a visual with Matrix expand collapse feature. I was successful in creating it. In development mode it works like a charm but when I try to package it, it gets stuck and expand collapse does not work on calling this.selectionManager.toggleExpandCollapse(nodeSelectionId) and the same throws error in desktop mode.

visuals-tools: 4.0.4
visuals-api: 4.1.0

I have given a link to the repo below and the data set I used.

https://github.com/vicktor3/matrixviz
[mode2AutoGen.csv](https://github.com/microsoft/PowerBI-visuals-tools/files/7918039/mode2AutoGen.csv)

Reference: https://docs.microsoft.com/en-us/power-bi/developer/visuals/dataview-mappings#expanding-and-collapsing-row-headers

**Comment by AleksSavelev** [comment]
@vicktor3 Thank you for this issue.

It should work fine in the newest version. 
You can reach out to pbicvsupport@microsoft.com or create a new issue if the problem still appears on your end.
