### ISSUE TITLE
Power BI custom visual date as string issue

### ISSUE THREAD

**Issue by smashmirrorcardboardface** [microsoft/PowerBI-visuals-tools#412]
I'm currently passing a data field into a custom visualisation of type 'Date'

I can see from the dataview in the custom vis toolbar that it is passed through as a bunch of functions and a epoch timestamp:
![image](https://user-images.githubusercontent.com/8159660/155200504-d9a6ad30-5cca-4b6a-9e8f-d2daf8d76434.png)
dataview with correct date

but when I try and log the same data from the options variable passed through to the public update function, I see this:
![image](https://user-images.githubusercontent.com/8159660/155200566-97c9f7f7-f3ec-4776-98f0-b803ac71c597.png)
console with dates as strings

as you can see the dates appear as strings. They are also strings in the code as far as I can tell.

If I rearrange the order of the category fields, they appear correctly: 
![image](https://user-images.githubusercontent.com/8159660/155200639-809b92c4-75c9-45a3-9740-32db84a2cbc8.png)

is this a bug or am I doing something stupid?? how do I work around it?

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com) with questions related to the development of custom visuals
