### ISSUE TITLE
async dependency in powerbi-visuals-tools 4.0.4

### ISSUE THREAD

**Issue by FoXTiSiTY** [microsoft/PowerBI-visuals-tools#415]
Hi,

I'm picking up 2 high vulnerabilities within the powerbi-visuals-tools@4.0.4 dependency that relates to the async@3.2.0 dependency. This has been fixed in >= async@3.2.2. 

Can this please be fixed?

![image](https://user-images.githubusercontent.com/12406751/163327900-20f214ff-f11c-4720-bcbf-13d07a126fd7.png)
![image](https://user-images.githubusercontent.com/12406751/163327926-3c3bcf74-27b6-46af-b2a6-4528a3999874.png)

**Comment by spreusler** [comment]
This is also a problem for us.

In particular, it affects the certification process. Without a fix, we cannot submit our visualization and receive a rejection:

"The npm audit command returns moderate or high level warnings. Please update the visual and re-submit your offer."

**Comment by DominikGa** [comment]
Same here.

**Comment by FoXTiSiTY** [comment]
@spreusler Yeah, we are busy with the certification process and also can't submit with this problem.

**Comment by Demonkratiy** [comment]
Sorry for a delay colleagues. We will publish new fix version very shortly. 
But just for information, about the certification process, to save your time in future, if there are any `npm audit` issues in the latest available `powerbi-visuals-tools`, so it is not your fault, you may proceed with certification process and submit your visual. Certification team should pass this moment. And to be 100% sure, you can also add a comment to the **"Notes for Certification"** and write a message to **_pbicvsupport@microsoft.com_**, describing the situation, so they will not miss that moment.

**Comment by spreusler** [comment]
Thank you @Demonkratiy ! Saw your pull request.
