### ISSUE TITLE
developer visual does not recieve update 

### ISSUE THREAD

**Issue by devadminpoweronbi** [microsoft/PowerBI-visuals-tools#442]
I am creating a custom visual but when I load it by refreshing the page or reloading the visual in edit mode, the visual does not receive update. 

It happens when I am using google chrome but sometimes happens with firefox as well. 
After restarting the browser it usually receives an update. but than again it wont work.
I am using chrome version 109.0.5414.75.
The size of the visual is formidable, the package size is bigger than 5 megabytes.

**Comment by Pathonet** [comment]
Sometimes it does help to restart the nodeJS server. So `ctrl+c` to stop running server in terminal and then `pbiviz start` to restart.
