### ISSUE TITLE
ssl certificate doesn't installs

### ISSUE THREAD

**Issue by Alexandervelilyaev** [microsoft/PowerBI-visuals-tools#448]
After version 4.0.5 ssl certificate doesn't installing. In the v4.0.5 we use pass phrase. Now it doesn't require pass phrase and certificate doesn't work. Please fix.

**Comment by j-murray1** [comment]
I can confirm this issue. In pbiviz v4.0.6+ there was a change where certificate file(s) are provided in the 'certs' folder during install. You can still run 'pbiviz --install-cert' and it states that it runs successfully (and does not ask for a passcode), but if you then try and package a custom visual you will be told your certificate is not valid. If you delete the install-provided certificate file(s) then execute 'pbiviz --install-cert' the process is identical to previous versions and the generated certificate is valid.

**Comment by Alexandervelilyaev** [comment]
@j-murray1 , thank you for the details. Could you please provide more details about this point: 
> "If you delete the install-provided certificate file(s)"
Where can I find them? 

Thank you in advance

**Comment by danglotor** [comment]
I can also confirm this issue. The certificate is called "PowerBICustomVisualTest_public.crt" so maybe it is some test version? I tried to delete the installed certificate and install it again multiple times, for user, for machine, automatically, manually... 
 powerbi-visuals-tools version - 4.3.0

**Comment by zBritva** [comment]
@Alexandervelilyaev  @danglotor Could you provide the error output?

Is there an error in loading the certificate to the storage of OS?
Is there an error in loading the certificate by browser (Browser says cert if not valid)?

There no changes in tools code related to certificates since Dec 1, 2021 according history of GitHub.

And why do you really need to install this certificate?

`pbiviz start` should also generate a certificate before starting dev server.

**Comment by j-murray1** [comment]
> @j-murray1 , thank you for the details. Could you please provide more details about this point:
> 
> > "If you delete the install-provided certificate file(s)"
> 
> Where can I find them?
> 
> Thank you in advance

Sorry for the delayed response on this. They are located in the certs folder of the powerbi-visuals-tools folder structure. Explicitly: npm/node_modules/powerbi-visuals-tools/certs

Hope this helps!
