### ISSUE TITLE
Error 404 fetching `pbiviz.json` with custom webpack config.

### ISSUE THREAD

**Issue by ElPrudi** [microsoft/PowerBI-visuals-tools#457]
Since powerbi-webpack-plugin version 3.2.0 the `pbiviz.json` file is no longer a webpack asset. Thing is, that it's documented anywhere and and I cant figure out from the commits what to change, so I try to open it here, because reverting to version 3.1.2 did nothing.

There is some change in the pbiviz command that prevents it from getting transferred to the backend assets folder.

**Comment by AleksSavelev** [comment]
Could you please provide us with your source code? So we'll be able to reproduce the issue.

You can send it to our email - pbicvsupport@microsoft.com.
