### ISSUE TITLE
Rapport montrant la répartition des produits de consommation en Côte d’Ivoire 

### ISSUE THREAD

**Issue by Sylvanus12** [microsoft/PowerBI-visuals-tools#470]
https://www.linkedin.com/posts/sylvanus-franck-olivier-ohouo-317974185_rapport-pr%C3%A9sentant-les-produits-de-consommation-activity-7018545665689432065-AvIS?utm_source=share&utm_medium=member_android

**Comment by AleksSavelev** [comment]
Could you, please, describe what problem you faced using PowerBI-visuals-tools?
