### ISSUE TITLE
Unable to create visual;

### ISSUE THREAD

**Issue by AakashMarasini** [microsoft/PowerBI-visuals-tools#475]

**Comment by AakashMarasini** [comment]
I am trying to create a new custom visual but I am getting errors such as:

 error  Unable to create visual.
 Error: Package install failed.

 installed versions are:
 node.js-version: v18.17.0
 powerbi-visuals-tools version - 4.3.2
 
 I could not figureout the reason for this issue. Please help me on this.
 
![image](https://github.com/microsoft/PowerBI-visuals-tools/assets/49764622/709a7d97-b961-41c7-b265-619b50a00452)

**Comment by AleksSavelev** [comment]
Hi @AakashMarasini,

Thank you for this issue reported. Have you tried to use the new version (5.0.2) of the tools?

**Comment by AakashMarasini** [comment]
Hi @AleksSavelev 

Yes, I have already tried version 5.0.2 and got the same issue. That's why I try to use 4.3.2 but still got the same issue in 4.3.2 as well. 
https://community.fabric.microsoft.com/t5/Custom-Visuals-Development/Unable-to-Create-Visual/m-p/3367104#M7850

![image](https://github.com/microsoft/PowerBI-visuals-tools/assets/49764622/1b17fb1b-34dd-48a7-a5ab-ddc15d231928)

**Comment by AleksSavelev** [comment]
Unfortunately, I wasn't able to reproduce the issue in my environment.

Looks like a repo was created but tools can't install the packages. Please confirm that folder was generated. If it was, try to open this repo and install packages manually.
