### ISSUE TITLE
Unable to create visual

### ISSUE THREAD

**Issue by UnremittingTerryWang** [microsoft/PowerBI-visuals-tools#479]
![image](https://github.com/microsoft/PowerBI-visuals-tools/assets/33817781/c044a273-6d84-4e96-8a7e-1822d2a99f42)
Package install failed. How to install package manually?

**Comment by AleksSavelev** [comment]
Thank you for reporting this issue. Please tell me what node version you use.

It looks like the visual folder 'circleCard' was created, so you can navigate into it and run `npm i`. Let me know if any errors will appear.
