### ISSUE TITLE
If a visual filtered by a date type field, then the selection is not working well.

### ISSUE THREAD

**Issue by devadminpoweronbi** [microsoft/PowerBI-visuals-tools#484]
We have a report, with 2 Table visuals with the same dataset. We filtered the first visual by many values of a datetime field. And we selected a row in the first visual from the filtered result. Then the second visual filtered by this selection, but we have no result in second visual.
![filter_bug_1](https://github.com/microsoft/PowerBI-visuals-tools/assets/124053701/a9f07d56-f410-403d-9e4f-eb8892abd519)
![filter_bug_2](https://github.com/microsoft/PowerBI-visuals-tools/assets/124053701/28d9462e-fa78-41cf-9a58-b9610f6ae192)

**Comment by AleksSavelev** [comment]
The issue isn't related to the Tools package. Feel free to contact [pbicvsupport@microsoft.com](mailto:pbicvsupport@microsoft.com) with questions related to the development of custom visuals
