### ISSUE TITLE
API 1.3.0 error

### ISSUE THREAD

**Issue by danieleperilli** [Microsoft/PowerBI-visuals-tools#49]
My custom visuals don't work with the API 1.3.0 (no third-party libraries involved)
Here is a screenshot of the error from Developer Tools:
![screenshot](https://cloud.githubusercontent.com/assets/9072177/19971157/8708e48c-a1de-11e6-9ac5-770ab3e38c54.png)

**Comment by raananzvi** [comment]
I'm sorry, but we don't have production support for API 1.3 just yet.
It will take several weeks. We are testing this internally first.
