### ISSUE TITLE
Passing query parameter to server

### ISSUE THREAD

**Issue by piedukexyz** [microsoft/PowerBI-visuals-tools#490]
Is it possible to pass a query parameter when running the nodejs server for the visual?

**Comment by AleksSavelev** [comment]
Unfortunately, it's not possible. Could you, please, describe the use case and why you need it?

**Comment by piedukexyz** [comment]
We're trying to use a integrate in a custom visual a script that requires indexeddb but we can pass it this parameter to make it skip. Another option to disable indexeddb could potentially work as well
