### ISSUE TITLE
Capabilitie of ImageUpload

### ISSUE THREAD

**Issue by luizzappa** [microsoft/PowerBI-visuals-tools#491]
There is a class called `ImageUpload`, inherited from `FormattingComponent`, that allows you to upload images. However, I can't figure out which `object` type I should include in the `capabilities.json` file to map.

![image](https://github.com/microsoft/PowerBI-visuals-tools/assets/65685842/53afded2-b0f7-4c0c-a0d4-3d473ea3bdda)

https://github.com/microsoft/powerbi-visuals-api/blob/bd9cfb3d19c05d510f790429aef91ec2f7698003/src/formatting-model-api.d.ts#L479

**Comment by AleksSavelev** [comment]
Unfortunately, this type isn't supported by Custom Visuals for now. You can see all supported types in the [capabilities schema](https://github.com/microsoft/powerbi-visuals-api/blob/main/schema.capabilities.json)
