### ISSUE TITLE
geolocation error - disabled by default (feature request)

### ISSUE THREAD

**Issue by HERVEBONNEL** [microsoft/PowerBI-visuals-tools#493]
I am trying to make an active map visual based on current position however a simple code in the constructor of a visual.ts requesting a geolocation results in error.

eg
`navigator.geolocation.getCurrentPosition(console.log)`

the log results in : "Geolocation error: Geolocation has been disabled in this document by permissions policy.."
There seems no way to set the policy in capabilities.json or otherwise.

If the same code is run from the console, the script generates the location coords object.

Same issues with other [CSP policies such as img-src](https://community.fabric.microsoft.com/t5/Developer/using-Leaflet-in-power-Bi-with-pbiviz-API-5-3-0/m-p/3497913) to load external tiles. More granular set up of CSP policies and other policies such as geolocation could be useful.

Please help with any workaround or feature addition.

**Comment by AleksSavelev** [comment]
Hello @HERVEBONNEL,
What version of powerbi-visuals-api do you use?

**Comment by HERVEBONNEL** [comment]
powerbi-visuals-tools version - 5.2.1

**Comment by HERVEBONNEL** [comment]
Hi @AleksSavelev, please let me know if there is workaround to this or possible to include feature. I tried API 5.3.0 and it s not working. I am wondering if the issue is with the encapsulation within the iframe which does not allow geolocalisation functions.

**Comment by AleksSavelev** [comment]
Hi @HERVEBONNEL, I'm sorry for the late response.

Try to add WebAccess to your privileges in capabilities.json
```json
    "privileges": [
        {
            "name": "WebAccess",
            "parameters": [
                "*"
            ]
        }
    ]
```

**Comment by HERVEBONNEL** [comment]
No success I am afraid. i am wondering if issue is <iframe allow="geolocation">

**Comment by AleksSavelev** [comment]
Oh, you're right. 
Unfortunately, it's not possible to enable this feature for custom visuals
