### ISSUE TITLE
The 'Show DatavView' button does not work

### ISSUE THREAD

**Issue by hienphamerp** [microsoft/PowerBI-visuals-tools#498]
Hi everyone,

I am following this tutorial from Microsoft Learn to create a Power BI circle card custom visual.

[Learn how to develop your own Power BI visual using the circle card visual as an example. - Power BI...](https://learn.microsoft.com/en-us/power-bi/developer/visuals/develop-circle-card)

But I am stucking on showing dataview.

When I press Show Dataview, nothing happens.

As you can see, the Show Dataview button already clicked.
https://community.fabric.microsoft.com/t5/image/serverpage/image-id/1012934i12CA4C3E0556DA48/image-size/medium?v=v2&px=400

Anyone has the same issue?

**Comment by AleksSavelev** [comment]
Hi @hienphamerp, thank you for the issue.

This problem is out of powerbi-visuals-tools scope, I would recommend to write on the support alias if you have such problems. But we'll try to provide you with the solution, let us investigate it.

**Comment by AleksSavelev** [comment]
After some investigation I can say that this is a bug with PowerBI. We've created an issue and assigned a responsible team. I hope it's going to be fixed as soon as possible. Thank you for reporting it.

Closing this issue, because the bug isn't related to tools itself.
