### ISSUE TITLE
Tutorial on creating an R-powered Power BI visual is not updated

### ISSUE THREAD

**Issue by lucazav** [microsoft/PowerBI-visuals-tools#499]
I noticed that the tutorial on how to create an R-powered Power BI visual ([here](https://learn.microsoft.com/en-us/power-bi/developer/visuals/create-r-based-power-bi-desktop)) has not been updated to pbiviz 5.3.0 (the current version).
This means that the default `settings.ts` template now uses a completely different object model than the one used in the tutorial.

I have opened an issue on GitHub here: https://github.com/MicrosoftDocs/powerbi-docs/issues/4933

In the meantime, while someone from Microsoft is updating the tutorial, does anyone know how to create the same dropdown static property used for the Data Look option in the custom visual of the tutorial?

**Comment by lucazav** [comment]
Hi all, any help on this? Thanks.

**Comment by AleksSavelev** [comment]
JFYI: I've prepared a new version of tools with fix of settings and sent documentation updates on review. I hope it to be updated during this week.

**Comment by AleksSavelev** [comment]
It should be up to date right now. 
@lucazav Could you please take a look and tell me if we missed something?
