### ISSUE TITLE
Using external libraries

### ISSUE THREAD

**Issue by SuperBobb** [microsoft/PowerBI-visuals-tools#50]
I'm trying to use an external library called 'request' inside my custom visual.
I've installed it and its dependencies:
```
npm i request -global
typings i dt~request --save --global
typings i dt~node --save --global
typings i dt~form-data --save --global
```
Still I cannot use it in my visual.ts file, because the `request` namespace is not visible there. 
If I add the `import * as request from 'request';` line on top of the visual.ts file then I can access that library's objects, but I get the following errors after pbiviz start:

>  info   Building visual...
>  error  TYPESCRIPT  /src/visual.ts : (4,36) Cannot find name 'IVisual'.
>  error  TYPESCRIPT  /src/visual.ts : (8,30) Cannot find name 'VisualConstructorOptions'.
>  error  TYPESCRIPT  /src/visual.ts : (14,32) Cannot find name 'VisualUpdateOptions'.
>  error  TYPESCRIPT  /visualPlugin.ts : (8,103) Property 'visual' does not exist on type 'typeof extensibility'.

I tried to use the `var request = require("request");` line and there were no compile time errors. Still I get this runtime exception:

> ReferenceError: 'require' is undefined

   
I see same issues when I'm trying to use some other external libraries (like `'rest'`, etc.). Meanwhile the `d3` external library is accessible and is working without any problems. 
Please help me with this issue. What is the proper way of referencing external libraries' objects in my custom visual code?

**Comment by raananzvi** [comment]
You should follow the steps in this GitHub sample visual: https://github.com/Microsoft/PowerBI-visuals-sampleUsingExternalLibraries

**Comment by SuperBobb** [comment]
Thank you for your answer.
I have followed this sample and have followed the article for referencing the `d3` library (https://github.com/Microsoft/PowerBI-visuals/blob/master/Tutorial/Typings.md).
Those steps are working fine for those libraries however they are not helping me with the `request` module. Apparently its definition or implementation differs somehow.
Could you try to create a new visual project, do the same steps and use that library in the visual.ts file? 
Or maybe you know another library that could help me with HTTP GET requests?

**Comment by raananzvi** [comment]
Several things:
1. Did you include the request library in the tsconfig.json file?
2. What API version are you targeting? Starting from API 1.2 you will not have D3 included in the IFRAME web page, and you will have to compile with D3 (add it to the tsconfig.json file)
3. Even if you will be able to properly compile and run with this library, I'm not sure the browser or remote server will allow you to invoke the HTTP GET request. Currently, custom visuals are sandboxed in such a way that they don't have a defined origin (origin = null), this will cause most servers to reject your requests.

**Comment by SuperBobb** [comment]
1. Yes, here an extract from my tsconfic.json file:
```
  "files": [
    ".api/v1.2.0/PowerBI-visuals.d.ts",
    "typings/index.d.ts",
    "node_modules/request/request.js",
    "src/visual.ts"
  ]
```
And from my typings/index.d.ts as well:
```
/// <reference path="globals/form-data/index.d.ts" />
/// <reference path="globals/node/index.d.ts" />
/// <reference path="globals/request/index.d.ts" />

```

2. The `pbiviz -V` gives me 1.2.1 version number.
The problem is not with the `D3` module but with the `request` one.

3. OK, I was afraid of something like that.
Still I would like to try it first.

**Comment by SuperBobb** [comment]
I've made these screenshots to be sure that I explain everything properly.
Here is the screenshot from VS Code when the import statement is commented out.
You can see that there is no objects from the `request` library even if it is referenced in the `index.d.ts` file:
![withoutimport](https://cloud.githubusercontent.com/assets/23281192/20140415/378e2972-a6b5-11e6-91e5-d4bac5bd36eb.png)
And here I uncommented the import statement. You can see that the default `request` function is there and referenced properly. 
![withimport](https://cloud.githubusercontent.com/assets/23281192/20140417/3b936bae-a6b5-11e6-9630-c8745df7c1d3.png)
But those red squiggles mark those error messages I've mentioned in the first post here:

> error TYPESCRIPT /src/visual.ts : (4,36) Cannot find name 'IVisual'.
> error TYPESCRIPT /src/visual.ts : (8,30) Cannot find name 'VisualConstructorOptions'.
> error TYPESCRIPT /src/visual.ts : (14,32) Cannot find name 'VisualUpdateOptions'.
> 

The request's index.d.ts is there and looks fine:
```
// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/658d360c6a8611e76f7cc75c07fcd0f02055ffc4/request/request.d.ts
declare module 'request' {
	import stream = require('stream');
	import http = require('http');
	import https = require('https');
	import url = require('url');
	import fs = require('fs');
	import FormData = require('form-data');

	namespace request {
		export interface RequestAPI<TRequest extends Request,
			TOptions extends CoreOptions,
			TUriUrlOptions> {

			defaults(options: TOptions): RequestAPI<TRequest, TOptions, RequiredUriUrl>;
			defaults(options: RequiredUriUrl & TOptions): DefaultUriUrlRequestApi<TRequest, TOptions, OptionalUriUrl>;

			(uri: string, options?: TOptions, callback?: RequestCallback): TRequest;
			(uri: string, callback?: RequestCallback): TRequest;
			(options: TUriUrlOptions & TOptions, callback?: RequestCallback): TRequest;
............
	}
	var request: request.RequestAPI<request.Request, request.CoreOptions, request.RequiredUriUrl>;
	export = request;
}

```
So how should I reference that library in my code?

**Comment by AviSander** [comment]
Please try to see if this blog helps http://blog.jongallant.com/2016/09/how-to-create-power-bi-custom-visual.html

**Comment by mmaitre314** [comment]
Cross-posting from https://github.com/Microsoft/PowerBI-visuals-tools/issues/50 since that might be a better place: Power BI seems to break external libraries like [vis.js](http://visjs.org/) that try to attach themselves to the `window` object.

**Comment by sfuchickie** [comment]
@helen508light were you able to resolve this? I am running into something similar but cannot find a straightforward answer.

**Comment by helen508light** [comment]
@sfuchickie what issue do you have?
