### ISSUE TITLE
API Dialog box

### ISSUE THREAD

**Issue by IgorVolod** [microsoft/PowerBI-visuals-tools#504]
Hi all!
API Dialog box...
The question here: 
https://community.fabric.microsoft.com/t5/Custom-Visuals-Ideas/Provide-ability-to-control-viewport-property-through-code-Custom/idc-p/622655#M293
Nikita Grachev: Please use Dialog Box API to place your components...
![Fig2](https://github.com/microsoft/PowerBI-visuals-tools/assets/129322210/51555622-6eae-41ea-9604-69e3a48339a3)
1. There is no way to set the style for the button. There is no option to remove a button.
2. There is no option to delete.
3. There is no possibility to change.
A designer designs my visual. I cannot deviate from a design project.
What should I do?

Thanks in advance for your answer.

**Comment by AleksSavelev** [comment]
Hi @IgorVolod,
Unfortunately, all of this are not supported yet. We are aware of the request for this feature and hope to see it implemented in the future.

**Comment by IgorVolod** [comment]
Fine! Are there any other options to achieve the desired result? I need to implement a slicer and a datepicker.

**Comment by AleksSavelev** [comment]
Could you, please, describe it more specific? You can implement both of it inside of your visual.

**Comment by IgorVolod** [comment]
The “datepicker” is located between interactive elements.
In the center, there is a date selection field.
There is no way to place a large visual element. The user opens the calendar by clicking it.
![fig3](https://github.com/microsoft/PowerBI-visuals-tools/assets/129322210/cc643b8e-423c-49f7-b8d4-933ed6519632)

**Comment by AleksSavelev** [comment]
Is it right, that you have a date selection field inside of your visual and you want to display a date picker on click? 
If so, you can handle it without dialog box, since it displays over all interface, but it's not required in your case. You can simply add a div block that contains picker and display it over your interactive elements inside of the visual.
