### ISSUE TITLE
PBIVIZ doesn't auto recompile on Windows, in OSX works well

### ISSUE THREAD

**Issue by danieleperilli** [microsoft/PowerBI-visuals-tools#52]
Hi,
the PBIVIZ tool never auto reloaded for me in Windows (so I have to terminate it and re start it continuously), so I supposed that the feature was never be implemented, but yesterday I tried to install the tool on my Mac and it works better! In fact, it  auto recompile and restart on each .ts file change. 
Is it my Windows machine or is it a known issue?
Thanks.

**Comment by helen508light** [comment]
already fixed
