### ISSUE TITLE
Show DataView button not working

### ISSUE THREAD

**Issue by njbemont** [microsoft/PowerBI-visuals-tools#520]
Hello,

I am attempting to work on a PBI Visual, and I was having trouble getting value formatting working. I try to click the Show Dataview button so I can see what format string is in the dataview column, but nothing happens when I click it and I get this error in the log:

Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at push.694582.B.loadVisual (web.clients.min.866063377bfe0670e29f.js:1:529832)
    at push.694582.B.toggleDataview (web.clients.min.866063377bfe0670e29f.js:1:531374)
    at HTMLElement.<anonymous> (web.clients.min.866063377bfe0670e29f.js:1:532914)
    at HTMLElement.dispatch (powerbiportal.smalldep.externals.bundle.min.26b5801df5e0b035e4a7.js:7:43090)
    at HTMLElement.<anonymous> (powerbiportal.smalldep.externals.bundle.min.26b5801df5e0b035e4a7.js:7:41074)
    at t.invokeTask (powerbiportal.smalldep.externals.bundle.min.26b5801df5e0b035e4a7.js:5:8996)
    at t.invokeTask (web.min.23743b7b7fccbc5d2a13.js:1:5498099)
    at web.min.23743b7b7fccbc5d2a13.js:1:5484044
    at de (web.min.23743b7b7fccbc5d2a13.js:1:5483733)
    at Object.onInvokeTask (web.min.23743b7b7fccbc5d2a13.js:1:5484020)
push.694582.B.loadVisual @ web.clients.min.866063377bfe0670e29f.js:1
push.694582.B.toggleDataview @ web.clients.min.866063377bfe0670e29f.js:1
(anonymous) @ web.clients.min.866063377bfe0670e29f.js:1
dispatch @ powerbiportal.smalldep.externals.bundle.min.26b5801df5e0b035e4a7.js:7
(anonymous) @ powerbiportal.smalldep.externals.bundle.min.26b5801df5e0b035e4a7.js:7
(anonymous) @ powerbiportal.smalldep.externals.bundle.min.26b5801df5e0b035e4a7.js:5
(anonymous) @ web.min.23743b7b7fccbc5d2a13.js:1
(anonymous) @ web.min.23743b7b7fccbc5d2a13.js:1
de @ web.min.23743b7b7fccbc5d2a13.js:1
onInvokeTask @ web.min.23743b7b7fccbc5d2a13.js:1
(anonymous) @ powerbiportal.smalldep.externals.bundle.min.26b5801df5e0b035e4a7.js:5
(anonymous) @ powerbiportal.smalldep.externals.bundle.min.26b5801df5e0b035e4a7.js:5
(anonymous) @ powerbiportal.smalldep.externals.bundle.min.26b5801df5e0b035e4a7.js:5
_ @ powerbiportal.smalldep.externals.bundle.min.26b5801df5e0b035e4a7.js:5
k @ powerbiportal.smalldep.externals.bundle.min.26b5801df5e0b035e4a7.js:5
w @ powerbiportal.smalldep.externals.bundle.min.26b5801df5e0b035e4a7.js:5

I attempted to retry with a fresh PBI visual template using pbiviz new (ProjectName), but I get the exact same error even with a fresh folder.

**Comment by AleksSavelev** [comment]
Hello @njbemont,

Unfortunately this is not possible to fix this issue from side of tools or visual. This is a known issue from PowerBI side, we are waiting it to be fixed.

**Comment by dm-p** [comment]
Hi @AleksSavelev - I just noticed this was closed down, and the button has been removed from the panel. Could the team please update the tutorial to reflect this change if it is not intended to be there anymore? [It is causing confusion amongst new developers](https://community.fabric.microsoft.com/t5/Custom-Visuals-Development/The-Show-Dataview-button-does-not-exists/m-p/4412219#M12194).

**Comment by AleksSavelev** [comment]
@dm-p Thanks for bringing attention to it. It'll be soon removed from the documentation.
