### ISSUE TITLE
Error during PBIVIZ installation.

### ISSUE THREAD

**Issue by Iran-Lima** [microsoft/PowerBI-visuals-tools#523]
I got the error message during PBIVIZ installation.

"npm error Class extends value undefined is not a constructor or null"

**Comment by AleksSavelev** [comment]
Hello @Iran-Lima,
Could you please provide some repro steps, such as:
1) Your environment details (OS version, Powershell version, Powerbi-visuals-tools version and node.js version)
2) What command do you run
3) And would be perfect to have sample repository that reproduce this issue
