### ISSUE TITLE
Cannot compile a Three.js Power BI visual

### ISSUE THREAD

**Issue by deevolutionism** [Microsoft/PowerBI-visuals-tools#59]
I'm trying to make a power bi visual using three.js.

I've installed a typings three.js library and have tried to build the most bare bones visual that includes setting up a canvas element and attaching a camera and scene. 

When I run pbiviz package from command prompt, it spits out this error:
`error TYPESCRIPT /src/visuals.ts : (31,24) Cannot find namespace 'THREE'.`

Are you able to compile a simple power bi visual that uses three.js?

**Comment by jonbgallant** [comment]
See this working example: https://www.dropbox.com/s/6hv48q0cqn0rot7/threejstest.zip?dl=0

**Comment by jonbgallant** [comment]
Blog post with step-by-step instructions: http://blog.jongallant.com/2017/01/powerbi-custom-visual-reference-threejs/

**Comment by HectorElMago** [comment]
> See this working example: https://www.dropbox.com/s/6hv48q0cqn0rot7/threejstest.zip?dl=0

Do you have this file, or another example? The link is not working.
