### ISSUE TITLE
case of new visual incorrect

### ISSUE THREAD

**Issue by wesyao** [Microsoft/PowerBI-visuals-tools#6]
When typing 
`pbiviz new PowerBI-visuals-asterPlot` the case of the project created incorrect.
![screen shot 2016-07-07 at 11 31 14 pm](https://cloud.githubusercontent.com/assets/16310155/16679279/286b8b0a-449b-11e6-8442-aee96a7f0639.png)

**Comment by spatney** [comment]
its camelcase. by design
