### ISSUE TITLE
Power BI custom visual plugin has been disabled

### ISSUE THREAD

**Issue by danly01** [microsoft/PowerBI-visuals-tools#64]
Followed the steps but ran into this issue. Not sure if I need admin rights to my profile.

 info   Building visual...
 info   Power BI custom visual plugin has been disabled
 done   build complete

 info   Starting server...
 info   Server listening on port 8080.

**Comment by xfuzzheadx** [comment]
Needed to install under an admin account and needed to check npm path with the following command: npm config set prefix <C:\Users\CI_USER\AppData\Roaming\npm>


http://stackoverflow.com/questions/38570209/making-global-npm-packages-available-to-all-users-on-windows-2012-server

**Comment by AleksSavelev** [comment]
Closing due to age
