### ISSUE TITLE
JSON change rebuild doesn't work when you change "visualClassName"

### ISSUE THREAD

**Issue by Kharms** [microsoft/PowerBI-visuals-tools#79]
To replicate:

Create a new pbiviz project `pbiviz new gihubIssue79`

Start pbiviz server `pbiviz start`

In pbiviz.json change `visualClassName:  "NewClassName"`

In terminal, you'll see

```
 info   JSON change detected. Rebuilding...
 done   JSON build complete
```

In visual.ts change `export class NewClassName implements IVisual {`

In terminal, you'll see

```
 info   Typescript change detected. Rebuilding...
 error  TYPESCRIPT  /src/visual.ts : (106,45) Cannot find name 'NewClassName'.
 error  TYPESCRIPT  /visualPlugin.ts : (8,154) Property 'NewClassName' does not exist on type 'typeof PBI_CV_GUIDGUIDGUIDGUIDGUID'.
```

**Comment by silverit** [comment]
In file pbiviz.json, set visualClassName: "NewClassName"

**Comment by AleksSavelev** [comment]
Closing due to age
