### ISSUE TITLE
`window.devicePixelRatio` fails in Firefox and Chrome 57

### ISSUE THREAD

**Issue by Knagis** [microsoft/PowerBI-visuals-tools#81]
Reading the value of `window.devicePixelRatio` throws an error in Firefox:

> TypeError: 'get devicePixelRatio' called on an object that does not implement interface Window.

It seems this might be caused by the same issue as was reported in #38 

```typescript
    export class Visual implements IVisual {
        constructor(options: VisualConstructorOptions) {
            console.log("devicePixelRatio test");
            try {
                console.log("devicePixelRatio ok", window.devicePixelRatio);
            } catch (e) {
                console.error("devicePixelRatio err", e);
            }
        }
    }
```

The same code works correctly on Chrome.

**Comment by Knagis** [comment]
This also happens now on Chrome 57.

**Comment by Trottsie** [comment]
Same issue here chrome 57 not working. This is having a significant impact.

**Comment by ghynes** [comment]
Any updates on this? It's a huge issue for us at the moment, breaking critical visualizations

**Comment by ignatvilesov** [comment]
The current workaround is to use ```window.window.devicePixelRatio```.

Please note we've created the [common issue](https://github.com/Microsoft/PowerBI-visuals/issues/165) to track the current status.
