### ISSUE TITLE
In api 1.5.0 enum VisualUpdateType.Resize = 32. On powerbi.com type = 36.

### ISSUE THREAD

**Issue by Kharms** [Microsoft/PowerBI-visuals-tools#83]
In .api/v1.5.0/PowerBI-visuals.d.ts

```
    enum VisualUpdateType {
        Data = 2,
        Resize = 4,
        ViewMode = 8,
        Style = 16,
        ResizeEnd = 32,
        All = 62,
    }
```

If you console.log() the `VisualUpdateOptions` in the update method of IVisual and resize some visual and look at the type, on resizeEnd `type: 36`

**Comment by Knagis** [comment]
the enum value is the bitwise combination of the possible flags. so the value you are seeing is `Resize | ResizeEnd = 4 | 32 = 36`. Which means that the event is both for the Resize *and* ResizeEnd events.
